;;; ogent-agent-execution-tests.el --- Fluent tool API tests -*- lexical-binding: t; -*-

;;; Commentary:
;; Exercise structured execution through the real registry and policy owners.

;;; Code:

(require 'ogent-test-helper)
(require 'ogent-agent nil t)
(require 'ogent-tools)
(require 'ogent-ui-toolcalls)
(require 'ogent-tool-results nil t)
(defvar gptel--known-tools)

(defun ogent-agent-execution-tests--file (root name text)
  "Create fixture NAME containing TEXT under ROOT."
  (let ((file (expand-file-name name root)))
    (make-directory (file-name-directory file) t)
    (with-temp-file file (insert text))
    file))

(ert-deftest ogent-agent-execution-read-structured-pages ()
  "Structured reads return exact positions, content and genuine JSON arrays."
  (let* ((root (ogent-test--provision-store-directory 'tools))
         (file (ogent-agent-execution-tests--file root "read.txt" "alpha\nbeta\ngamma\n"))
         (ogent-tool-registry (copy-tree ogent-tools-default-registry))
         (result (ogent-agent-call "read_file" (list :file_path file :limit 2)))
         (data (plist-get result :data)))
    (should (equal (plist-get result :status) "ok"))
    (should (equal (plist-get data :content) "alpha\nbeta"))
    (should (= (plist-get data :total_lines) 3))
    (should (= (plist-get data :next_offset) 3))
    (should (vectorp (plist-get data :lines)))
    (should (equal (plist-get (json-parse-string (ogent-tool--read-file file 3 2 'json)
                                                 :object-type 'plist) :content) "gamma"))
    (should (string-match-p "1\talpha" (ogent-tool--read-file file 1 2)))))

(ert-deftest ogent-agent-execution-read-long-line-continuation ()
  "A bounded long-line page retains every character through continuation."
  (let* ((root (ogent-test--provision-store-directory 'tools))
         (file (ogent-agent-execution-tests--file root "long.txt" "abcdefghij\nlast\n"))
         (ogent-tools-max-output-chars 4)
         (first (ogent-tool-results-read file 1 20))
         (second (ogent-tool-results-read file (plist-get first :next_offset) 20
                                          (plist-get first :next_column))))
    (should (equal (plist-get first :content) "abcd"))
    (should (= (plist-get first :next_offset) 1))
    (should (= (plist-get first :next_column) 5))
    (should (equal (plist-get second :content) "efgh"))
    (should (equal (plist-get first :snapshot) (plist-get second :snapshot)))))

(ert-deftest ogent-agent-execution-read-empty-and-invalid ()
  "Empty files have no invented lines, and invalid positions remain typed."
  (let* ((root (ogent-test--provision-store-directory 'tools))
         (file (ogent-agent-execution-tests--file root "empty.txt" ""))
         (ogent-tool-registry (copy-tree ogent-tools-default-registry))
         (data (plist-get (ogent-agent-call "read-file" (list :file_path file)) :data)))
    (should (equal (plist-get data :lines) []))
    (should (eq (plist-get data :has_more) :json-false))
    (should (equal (plist-get (ogent-agent-call "read-file" (list :file_path file :offset 2)) :status)
                   "error"))))

(ert-deftest ogent-agent-execution-read-respects-configured-default ()
  "Use a smaller configured line budget without requiring explicit limits."
  (let* ((root (ogent-test--provision-store-directory 'tools))
         (file (ogent-agent-execution-tests--file root "small.txt" "a\nb\nc\n"))
         (ogent-tools-max-file-lines 2)
         (ogent-tool-registry (copy-tree ogent-tools-default-registry))
         (result (ogent-agent-call "read" (list :file_path file))))
    (should (equal (plist-get result :status) "ok"))
    (should (= (plist-get (plist-get result :data) :limit) 2))
    (should (equal (plist-get (plist-get (ogent-agent-next result) :data) :content) "c"))))

(ert-deftest ogent-agent-execution-glob-complete-pagination ()
  "File discovery exposes every result beyond the previous 100-file cap."
  (let* ((root (ogent-test--provision-store-directory 'tools))
         (ogent-tool-registry (copy-tree ogent-tools-default-registry)))
    (dotimes (index 105)
      (ogent-agent-execution-tests--file root (format "%03d.el" index) ""))
    (let* ((first (plist-get (ogent-agent-call "glob" (list :pattern "*.el" :path root)) :data))
           (last (plist-get (ogent-agent-call "glob" (list :pattern "*.el" :path root :offset 100)) :data)))
      (should (= (plist-get first :total_files) 105))
      (should (= (length (plist-get first :files)) 100))
      (should (= (length (plist-get last :files)) 5))
      (should (eq (plist-get last :has_more) :json-false))
      (should (equal (plist-get first :snapshot) (plist-get last :snapshot))))
    (should (string-match-p "Showing 100 of 105" (ogent-tool--glob "*.el" root)))))

(ert-deftest ogent-agent-execution-glob-json-empty-and-weird-paths ()
  "Empty arrays and paths containing newlines survive the JSON interface."
  (let* ((root (ogent-test--provision-store-directory 'tools))
         (file (ogent-agent-execution-tests--file root "colon:new\nline.el" ""))
         (data (json-parse-string (ogent-tool--glob "*.el" root 'json) :object-type 'plist)))
    (should (equal (plist-get (aref (plist-get data :files) 0) :path) file))
    (should (equal (plist-get (ogent-tool-results-glob "*.txt" root) :files) []))
    (should-error (ogent-tool-results-glob "*.el" root 2) :type 'user-error)))

(ert-deftest ogent-agent-execution-glob-star-stays-in-component ()
  "A single glob star never consumes another directory component."
  (let* ((root (ogent-test--provision-store-directory 'tools))
         (direct (ogent-agent-execution-tests--file root "foo/direct.el" "")))
    (ogent-agent-execution-tests--file root "foo/deep/nested.el" "")
    (should (equal (ogent-tools--glob-files "**/foo/*.el" root) (list direct)))
    (should-not (ogent-tools--glob-match-p "**/foo/[ -~]*.el" "foo/deep/nested.el"))))

(ert-deftest ogent-agent-execution-next-freezes-path-and-follows-json ()
  "Continuation calls retain absolute targets when the working root changes."
  (let* ((root (ogent-test--provision-store-directory 'tools))
         (other (ogent-test--provision-store-directory 'tools))
         (ogent-tools-project-root root)
         (ogent-tool-registry (copy-tree ogent-tools-default-registry)))
    (ogent-agent-execution-tests--file root "data.txt" "a\nb\nc\n")
    (ogent-agent-execution-tests--file other "data.txt" "wrong\n")
    (let ((first (ogent-agent-call "read_file" '(:file_path "data.txt" :limit 1) 'json)))
      (let* ((ogent-tools-project-root other)
             (second (ogent-agent-next first))
             (third (ogent-agent-next second)))
        (should (equal (plist-get (plist-get second :data) :content) "b"))
        (should (equal (plist-get (plist-get third :data) :content) "c"))
        (should (equal (plist-get (ogent-agent-next third) :status) "done"))))))

(ert-deftest ogent-agent-execution-next-refuses-changed-snapshot ()
  "Changed file pages are discarded with an explicit restart instruction."
  (let* ((root (ogent-test--provision-store-directory 'tools))
         (file (ogent-agent-execution-tests--file root "data.txt" "a\nb\n"))
         (ogent-tool-registry (copy-tree ogent-tools-default-registry))
         (first (ogent-agent-call "read-file" (list :file_path file :limit 1))))
    (with-temp-file file (insert "a\nchanged\n"))
    (let ((result (ogent-agent-next first)))
      (should (equal (plist-get (plist-get result :error) :code) "snapshot_changed"))
      (should (eq (plist-get result :data) :json-null)))))

(ert-deftest ogent-agent-execution-next-retains-long-line-characters ()
  "Following pages reconstructs long lines without dropping characters."
  (let* ((root (ogent-test--provision-store-directory 'tools))
         (file (ogent-agent-execution-tests--file root "data.txt" "abcdefghij"))
         (ogent-tools-max-output-chars 3)
         (ogent-tool-registry (copy-tree ogent-tools-default-registry))
         (page (ogent-agent-call "read-file" (list :file_path file)))
         (content ""))
    (while (equal (plist-get page :status) "ok")
      (setq content (concat content (plist-get (plist-get page :data) :content))
            page (ogent-agent-next page)))
    (should (equal content "abcdefghij"))))

(ert-deftest ogent-agent-execution-aliases-share-policy ()
  "Common verbs resolve exactly and cannot bypass a canonical denial."
  (let ((ogent-tool-registry (copy-tree ogent-tools-default-registry))
        (ogent-tool--denied-tools '("bash"))
        (ogent-tool-require-approval t))
    (should (eq (ogent-tool--name-symbol "read") 'read-file))
    (should (eq (ogent-tool--name-symbol "find") 'glob))
    (should (eq (ogent-tool--name-symbol "search") 'grep))
    (should (equal (plist-get (ogent-agent-call "shell" '(:command "printf unsafe")) :status) "denied"))
    (let ((error-data (plist-get (ogent-agent-call "shll" nil) :error)))
      (should (equal (plist-get error-data :code) "unknown_tool"))
      (should (string-match-p "did you mean shell" (plist-get error-data :message))))))

(ert-deftest ogent-agent-execution-aliases-exact-and-ambiguous ()
  "Exact registrations win and ambiguous declared aliases never execute."
  (let ((ogent-tool-registry
         '((:name alpha :aliases ["shared" "exact"])
           (:name beta :aliases ["shared"])
           (:name exact))))
    (should (eq (ogent-tool--name-symbol "exact") 'exact))
    (should-not (ogent-tool-spec-get "shared"))))

(ert-deftest ogent-agent-execution-process-grep-integration ()
  "Structured search participates in the same one-call pagination contract."
  (let* ((root (ogent-test--provision-store-directory 'tools))
         (file (ogent-agent-execution-tests--file root "colon:new\nline.txt" "needle\nneedle\nneedle\n"))
         (ogent-tool-registry (copy-tree ogent-tools-default-registry))
         (first (ogent-agent-call "search" (list :pattern "needle" :path root :limit 2)))
         (last (ogent-agent-next first)))
    (should (equal (plist-get first :status) "ok"))
    (should (= (plist-get (plist-get first :data) :total_matches) 3))
    (should (equal (plist-get (aref (plist-get (plist-get last :data) :matches) 0) :path) file))
    (should (= (plist-get (aref (plist-get (plist-get last :data) :matches) 0) :line) 3))
    (should (vectorp (plist-get (ogent-tool--grep "needle" file nil 0 'plist) :matches)))))

(ert-deftest ogent-agent-execution-process-shell-failures-retain-data ()
  "Nonzero exits and timeouts are typed failures with retained diagnostics."
  (let ((ogent-tool-registry (copy-tree ogent-tools-default-registry))
        (ogent-tool-require-approval nil))
    (let ((failed (ogent-agent-call "shell" '(:command "printf out; printf err >&2; exit 7")))
          (timed (ogent-agent-call "shell" '(:command "printf partial; sleep 2" :timeout 0.1))))
      (should (equal (plist-get (plist-get failed :error) :code) "command_failed"))
      (should (= (plist-get (plist-get failed :data) :exit_code) 7))
      (should (equal (plist-get (plist-get failed :data) :stderr) "err"))
      (should (equal (plist-get (plist-get timed :error) :code) "timeout"))
      (should (equal (plist-get (plist-get timed :data) :stdout) "partial")))))

(ert-deftest ogent-agent-execution-async-real-process-and-ledger ()
  "Async SDK calls return immediately and record one terminal result."
  (let ((ogent-tool-registry (copy-tree ogent-tools-default-registry))
        (ogent-tool-require-approval nil)
        (starts 0) (finishes 0) (callbacks 0) result)
    (cl-letf (((symbol-function 'ogent-ledger-record-tool-start)
               (lambda (&rest _) (cl-incf starts)))
              ((symbol-function 'ogent-ledger-record-tool-finish)
               (lambda (&rest _) (cl-incf finishes))))
      (let ((process (ogent-agent-call-async
                      "shell" '(:command "sleep 0.1; printf complete")
                      (lambda (data) (cl-incf callbacks) (setq result data)) 'json)))
        (should (processp process))
        (should (= callbacks 0))
        (while (process-live-p process) (accept-process-output process 0.05))
        (accept-process-output nil 0.05)
        (should (= callbacks 1))
        (should (= starts 1))
        (should (= finishes 1))
        (should (equal (plist-get (json-parse-string result :object-type 'plist) :status) "ok"))))))

(ert-deftest ogent-agent-execution-async-custom-once-and-sync-rejection ()
  "Native async tools receive callbacks and cannot execute synchronously."
  (let* ((runs 0)
         (ogent-tool-registry
          (list (list :name 'delayed :async t :args nil
                      :function (lambda (callback)
                                  (cl-incf runs) (funcall callback "first")
                                  (funcall callback "second") (error "After terminal")))))
         (ogent-tool-require-approval nil)
         (callbacks 0) result)
    (should (equal (plist-get (plist-get (ogent-agent-call "delayed" nil) :error) :code) "async_required"))
    (should (= runs 0))
    (ogent-agent-call-async "delayed" nil (lambda (data) (cl-incf callbacks) (setq result data)))
    (should (= callbacks 1))
    (should (equal (plist-get (plist-get result :data) :value) "first"))))

(defun ogent-agent-execution-tests--wait-process (process)
  "Wait for real PROCESS to finish within a bounded test deadline."
  (should (processp process))
  (let ((deadline (+ (float-time) 3)))
    (while (and (process-live-p process) (< (float-time) deadline))
      (accept-process-output process 0.01)))
  (should-not (process-live-p process))
  (accept-process-output nil 0.05))

(defun ogent-agent-execution-tests--break-ledger-file (file)
  "Make original ledger FILE unwritable and return its retained start copy."
  (let ((started (concat file ".started")))
    (rename-file file started)
    (make-directory file)
    started))

(ert-deftest ogent-agent-execution-async-ledger-write-failure-retains-terminal ()
  "Real finish write failures deliver SDK and gptel results without reruns."
  (dolist (format '(plist json gptel-json))
    (let* ((root (ogent-test--provision-store-directory 'tools))
           (file (expand-file-name "ledger.org" root))
           (effect (expand-file-name "effect.txt" root))
           (command (format "sleep 0.05; printf effect >> %s; printf complete; printf diagnostic >&2"
                            (shell-quote-argument effect)))
           (ogent-tool-registry (copy-tree ogent-tools-default-registry))
           (ogent-tool-require-approval nil)
           (ogent-tools--active-processes nil)
           (ogent-ledger-enabled t) (ogent-ledger-file file)
           (callbacks 0) result
           (callback (lambda (data) (cl-incf callbacks) (setq result data)))
           (process
            (if (eq format 'gptel-json)
                (let ((spec (ogent-tool-spec-get 'bash)))
                  (plist-put spec :async t)
                  (funcall (ogent-tool-execution-wrapper spec 'json) callback command nil 1))
              (ogent-agent-call-async "shell" (list :command command :timeout 1)
                                      callback format))))
      (should (file-exists-p file))
      (setq file (ogent-agent-execution-tests--break-ledger-file file))
      (ogent-agent-execution-tests--wait-process process)
      (unless (eq format 'plist)
        (setq result (json-parse-string result :object-type 'plist)))
      (should (= callbacks 1))
      (should (equal (plist-get result :status) "error"))
      (should (equal (plist-get (plist-get result :data) :stdout) "complete"))
      (should (equal (plist-get (plist-get result :data) :stderr) "diagnostic"))
      (should (= (plist-get (plist-get result :data) :exit_code) 0))
      (should (equal (plist-get (plist-get result :error) :code) "ledger_write_failed"))
      (should (string-match-p "already completed" (plist-get (plist-get result :error) :recovery)))
      (should (string-match-p "Do not rerun" (plist-get (plist-get result :error) :recovery)))
      (should-not (process-get process 'ogent-callback-error))
      (should-not ogent-tools--active-processes)
      (should (equal (with-temp-buffer (insert-file-contents effect) (buffer-string)) "effect"))
      (let ((ledger (with-temp-buffer (insert-file-contents file) (buffer-string))))
        (should (string-match-p "tool-start" ledger))
        (should-not (string-match-p "tool-finish" ledger))))))

(ert-deftest ogent-agent-execution-async-ledger-records-success ()
  "Successful async completion still appends a real ledger terminal."
  (let* ((root (ogent-test--provision-store-directory 'tools))
         (ogent-ledger-file (expand-file-name "ledger.org" root))
         (ogent-ledger-enabled t)
         (ogent-tool-registry (copy-tree ogent-tools-default-registry))
         (ogent-tool-require-approval nil) result
         (process (ogent-agent-call-async "shell" '(:command "printf complete")
                                          (lambda (data) (setq result data)))))
    (ogent-agent-execution-tests--wait-process process)
    (should (equal (plist-get result :status) "ok"))
    (let ((ledger (with-temp-buffer (insert-file-contents ogent-ledger-file) (buffer-string))))
      (should (string-match-p "tool-start" ledger))
      (should (string-match-p "tool-finish" ledger)))))

(ert-deftest ogent-agent-execution-legacy-async-ledger-failure-visible-once ()
  "Legacy callbacks retain real process output and a visible ledger warning."
  (let* ((root (ogent-test--provision-store-directory 'tools))
         (file (expand-file-name "ledger.org" root))
         (effect (expand-file-name "effect.txt" root))
         (spec (list :name 'legacy-process :async t
                     :args '((:name "command" :type "string"))
                     :function
                     (lambda (command callback)
                       (ogent-tool-process-bash-async
                        command nil 1
                        (lambda (data failure)
                          (funcall callback (plist-get data :stdout)
                                   (and failure (error-message-string failure)))
                          (funcall callback "duplicate"))))))
         (ogent-tool-registry (list spec))
         (ogent-tool-require-approval nil)
         (ogent-tools--active-processes nil)
         (ogent-ledger-enabled t) (ogent-ledger-file file)
         (callbacks 0) result
         (process (progn
                    (funcall (ogent-tool-execution-wrapper spec 'text)
                             (lambda (data) (cl-incf callbacks) (setq result data))
                             (format "sleep 0.05; printf effect >> %s; printf complete"
                                     (shell-quote-argument effect)))
                    (caar ogent-tools--active-processes))))
    (should (file-exists-p file))
    (setq file (ogent-agent-execution-tests--break-ledger-file file))
    (ogent-agent-execution-tests--wait-process process)
    (should (= callbacks 1))
    (should (string-prefix-p "complete\n[Ledger warning:" result))
    (should (string-match-p "already completed" result))
    (should (string-match-p "Do not rerun" result))
    (should-not (string-match-p "duplicate" result))
    (should-not (process-get process 'ogent-callback-error))
    (should-not ogent-tools--active-processes)
    (should (equal (with-temp-buffer (insert-file-contents effect) (buffer-string)) "effect"))))

(ert-deftest ogent-agent-execution-sync-ledger-failure-retains-completed-data ()
  "Sync storage failures retain data and distinguish actual tool failures."
  (dolist (exit-code '(0 7))
    (let* ((root (ogent-test--provision-store-directory 'tools))
           (file (expand-file-name "ledger.org" root))
           (ogent-ledger-enabled t) (ogent-ledger-file file)
           (runs 0)
           (spec (list :name 'ledger-sync :args nil :function #'ignore
                       :result-function (lambda ()
                                          (cl-incf runs)
                                          (should (file-exists-p file))
                                          (ogent-agent-execution-tests--break-ledger-file file)
                                          (list :stdout "completed" :exit_code exit-code))))
           (ogent-tool-registry (list spec))
           (ogent-tool-require-approval nil)
           (result (ogent-agent-call "ledger-sync" nil))
           (error-data (plist-get result :error)))
      (should (= runs 1))
      (should (equal (plist-get (plist-get result :data) :stdout) "completed"))
      (should (= (plist-get (plist-get result :data) :exit_code) exit-code))
      (should (equal (plist-get error-data :code) "ledger_write_failed"))
      (if (= exit-code 0)
          (should-not (plist-get error-data :tool_error))
        (should (equal (plist-get (plist-get error-data :tool_error) :code) "command_failed"))))))

(ert-deftest ogent-agent-execution-async-malformed-result-delivers-once ()
  "Result construction errors preserve completed extension data once."
  (let* ((data '(:has_more t :content "completed"))
         (spec (list :name 'read-file :async t
                     :args '((:name "path" :type "integer"))
                     :result-function #'ignore
                     :function (lambda (_path callback)
                                 (funcall callback data)
                                 (funcall callback "duplicate"))))
         (ogent-tool-registry (list spec))
         (ogent-tool-require-approval nil) (callbacks 0) result)
    (ogent-agent-call-async "read-file" '(:path 42)
                            (lambda (data) (cl-incf callbacks) (setq result data)))
    (should (= callbacks 1))
    (should (equal (plist-get result :data) data))
    (should (equal (plist-get (plist-get result :error) :code) "unsupported_result"))))

(ert-deftest ogent-agent-execution-async-immediate-result-returns-nil ()
  "Immediate native completion delivers once and returns no process handle."
  (let* ((spec (list :name 'immediate :async t :args nil
                     :function (lambda (callback) (funcall callback "completed"))))
         (ogent-tool-registry (list spec))
         (ogent-tool-require-approval nil) (callbacks 0) result)
    (should-not (ogent-agent-call-async
                 "immediate" nil
                 (lambda (data) (cl-incf callbacks) (setq result data))))
    (should (= callbacks 1))
    (should (equal (plist-get (plist-get result :data) :value) "completed"))))

(ert-deftest ogent-agent-execution-async-ledger-failure-preserves-tool-error ()
  "A reported tool error and its completed data survive a finish write failure."
  (let* ((root (ogent-test--provision-store-directory 'tools))
         (file (expand-file-name "ledger.org" root))
         (ogent-ledger-enabled t) (ogent-ledger-file file)
         (spec (list :name 'terminal-failure :async t :args nil :result-function #'ignore
                     :function (lambda (callback)
                                 (should (file-exists-p file))
                                 (ogent-agent-execution-tests--break-ledger-file file)
                                 (funcall callback '(:stdout "completed") '(error "Reported tool error"))
                                 (funcall callback "duplicate"))))
         (ogent-tool-registry (list spec))
         (ogent-tool-require-approval nil) (callbacks 0) result)
    (should-not (ogent-agent-call-async
                 "terminal-failure" nil
                 (lambda (data) (cl-incf callbacks) (setq result data))))
    (should (= callbacks 1))
    (should (equal (plist-get (plist-get result :data) :stdout) "completed"))
    (let ((error-data (plist-get result :error)))
      (should (equal (plist-get error-data :code) "ledger_write_failed"))
      (should (equal (plist-get (plist-get error-data :tool_error) :code) "execution_failed"))
      (should (equal (plist-get (plist-get error-data :tool_error) :message) "Reported tool error")))))

(ert-deftest ogent-agent-execution-ledger-start-failure-prevents-effects ()
  "An actual start write failure delivers an error without running the tool."
  (let* ((root (ogent-test--provision-store-directory 'tools))
         (ogent-ledger-enabled t) (ogent-ledger-file root)
         (runs 0)
         (spec (list :name 'ledger-start :async t :args nil
                     :function (lambda (callback)
                                 (cl-incf runs)
                                 (funcall callback "completed"))))
         (ogent-tool-registry (list spec))
         (ogent-tool-require-approval nil) (callbacks 0) result)
    (should-not (ogent-agent-call-async
                 "ledger-start" nil
                 (lambda (data) (cl-incf callbacks) (setq result data))))
    (should (= runs 0))
    (should (= callbacks 1))
    (should (equal (plist-get result :status) "error"))
    (should (equal (plist-get (plist-get result :error) :code) "execution_failed"))
    (should-not (string-match-p "already completed" (plist-get (plist-get result :error) :message)))))

(defun ogent-agent-execution-tests--assert-ledger-pair (file)
  "Assert exactly one start and finish event in actual ledger FILE."
  (with-temp-buffer
    (insert-file-contents file)
    (should (= (count-matches "^:OGENT_LEDGER_TYPE: tool-start$" (point-min) (point-max)) 1))
    (should (= (count-matches "^:OGENT_LEDGER_TYPE: tool-finish$" (point-min) (point-max)) 1))))

(ert-deftest ogent-agent-execution-async-ledger-context-survives-project-switch ()
  "SDK, JSON and legacy async calls keep paired events at their start origin."
  (dolist (format '(plist json gptel-json text))
    (dolist (initially-enabled '(t nil))
      (dolist (change-settings '(t nil))
	(let* ((origin (ogent-test--provision-store-directory 'tools))
               (other (ogent-test--provision-store-directory 'tools))
               (file (expand-file-name ".ogent/ledger.org" origin))
               (effect (expand-file-name "effect.txt" origin))
               (command (format "sleep 0.05; printf effect >> %s; printf complete"
				(shell-quote-argument effect)))
               (ogent-ledger-enabled initially-enabled)
               (ogent-ledger-file ".ogent/ledger.org")
               (ogent-tools-project-root origin)
               (ogent-tool-registry (copy-tree ogent-tools-default-registry))
               (ogent-tool-require-approval nil)
               (ogent-tools--active-processes nil)
               (callbacks 0) result callback-directory callback-enabled callback-file process
               (callback (lambda (data)
                           (cl-incf callbacks)
                           (setq result data callback-directory default-directory
				 callback-enabled ogent-ledger-enabled callback-file ogent-ledger-file))))
          (let ((default-directory origin))
            (setq process
                  (pcase format
                    ('gptel-json
                     (let ((spec (ogent-tool-spec-get 'bash)))
                       (plist-put spec :async t)
                       (funcall (ogent-tool-execution-wrapper spec 'json) callback command nil 1)))
                    ('text
                     (let ((spec (list :name 'legacy-process :async t
                                       :args '((:name "command" :type "string"))
                                       :function
                                       (lambda (shell-command complete)
					 (ogent-tool-process-bash-async
                                          shell-command nil 1
                                          (lambda (data failure)
                                            (funcall complete (plist-get data :stdout)
                                                     (and failure (error-message-string failure)))))))))
                       (setq ogent-tool-registry (list spec))
                       (funcall (ogent-tool-execution-wrapper spec 'text) callback command)
                       (caar ogent-tools--active-processes)))
                    (_ (ogent-agent-call-async "shell" (list :command command :timeout 1)
                                               callback format)))))
          (should (eq (file-exists-p file) initially-enabled))
          (when change-settings
            (setq ogent-ledger-enabled (not initially-enabled) ogent-ledger-file "future.org"))
          (let ((default-directory other))
            (ogent-agent-execution-tests--wait-process process)
            (should (= callbacks 1))
            (should (equal callback-directory other))
            (should (eq callback-enabled (if change-settings (not initially-enabled) initially-enabled)))
            (should (equal callback-file (if change-settings "future.org" ".ogent/ledger.org")))
            (pcase format
              ('text (should (equal result "complete")))
              (_
               (unless (eq format 'plist)
		 (setq result (json-parse-string result :object-type 'plist)))
               (should (equal (plist-get result :status) "ok"))
               (should (equal (plist-get (plist-get result :data) :stdout) "complete"))))
            (should-not (process-get process 'ogent-callback-error))
            (should-not ogent-tools--active-processes)
            (should (equal (with-temp-buffer (insert-file-contents effect) (buffer-string)) "effect"))
            (if initially-enabled
		(ogent-agent-execution-tests--assert-ledger-pair file)
              (should-not (file-exists-p file)))
            (should-not (file-exists-p (expand-file-name ".ogent/ledger.org" other)))
            (should-not (file-exists-p (expand-file-name "future.org" other)))
            ;; A later call uses the new enabled state and destination in B.
            (push (list :name 'future :args nil :function (lambda () "future")) ogent-tool-registry)
            (should (equal (plist-get (ogent-agent-call "future" nil) :status) "ok"))
            (let ((future-file (expand-file-name ogent-ledger-file other)))
              (if ogent-ledger-enabled
                  (ogent-agent-execution-tests--assert-ledger-pair future-file)
		(should-not (file-exists-p future-file))))
            (should-not (file-exists-p (expand-file-name "future.org" origin)))
            (when initially-enabled
              (ogent-agent-execution-tests--assert-ledger-pair file))))))))

(ert-deftest ogent-agent-execution-sync-ledger-context-survives-tool-context-change ()
  "Sync tools changing ambient settings keep their original ledger context."
  (dolist (format '(plist json text))
    (dolist (initially-enabled '(t nil))
      (dolist (change-settings '(t nil))
	(let* ((origin (ogent-test--provision-store-directory 'tools))
               (other (ogent-test--provision-store-directory 'tools))
               (file (expand-file-name ".ogent/ledger.org" origin))
               (effect (expand-file-name "effect.txt" origin))
               (ogent-ledger-enabled initially-enabled)
               (ogent-ledger-file ".ogent/ledger.org")
               (runs 0)
               (execute (lambda ()
                          (cl-incf runs)
                          (with-temp-buffer (insert "effect") (append-to-file (point-min) (point-max) effect))
                          (setq default-directory other)
                          (when change-settings
                            (setq ogent-ledger-file "future.org"
                                  ogent-ledger-enabled (not initially-enabled)))))
               (spec (list :name 'context-changing :args nil
                           :function (lambda () (funcall execute) "complete")
                           :result-function (lambda () (funcall execute) '(:stdout "complete"))))
               (ogent-tool-registry (list spec))
               (ogent-tool-require-approval nil))
          (let* ((default-directory origin)
		 (result (if (eq format 'text)
                             (funcall (ogent-tool-execution-wrapper spec 'text))
                           (ogent-agent-call "context-changing" nil format))))
            (should (= runs 1))
            (should (equal default-directory other))
            (should (equal ogent-ledger-file (if change-settings "future.org" ".ogent/ledger.org")))
            (should (eq ogent-ledger-enabled (if change-settings (not initially-enabled) initially-enabled)))
            (if (eq format 'text)
		(should (equal result "complete"))
              (when (eq format 'json) (setq result (json-parse-string result :object-type 'plist)))
              (should (equal (plist-get result :status) "ok"))
              (should (equal (plist-get (plist-get result :data) :stdout) "complete")))
            (should (equal (with-temp-buffer (insert-file-contents effect) (buffer-string)) "effect"))
            (if initially-enabled
		(ogent-agent-execution-tests--assert-ledger-pair file)
              (should-not (file-exists-p file)))
            (should-not (file-exists-p (expand-file-name ".ogent/ledger.org" other)))
            (should-not (file-exists-p (expand-file-name "future.org" other)))
            (should-not (file-exists-p (expand-file-name "future.org" origin)))))))))

(ert-deftest ogent-agent-execution-async-denial-and-cancel ()
  "Async denials do not start processes and cancellation retains output."
  (let ((ogent-tool-registry (copy-tree ogent-tools-default-registry))
        (ogent-tool--denied-tools '("bash"))
        (ogent-tool-require-approval t)
        (callbacks 0) result)
    (should-not (ogent-agent-call-async "shell" '(:command "sleep 2")
					(lambda (data) (cl-incf callbacks) (setq result data))))
    (should (= callbacks 1))
    (should (equal (plist-get result :status) "denied"))
    (let* ((ogent-tool-require-approval nil)
           (process (ogent-agent-call-async
                     "shell" '(:command "printf partial; sleep 2")
                     (lambda (data) (setq result data)))))
      (accept-process-output process 0.05)
      (ogent-tool-process-cancel process)
      (accept-process-output nil 0.05)
      (should (equal (plist-get (plist-get result :error) :code) "cancelled"))
      (should (equal (plist-get (plist-get result :data) :stdout) "partial")))))

(ert-deftest ogent-agent-execution-async-and-sync-failures-in-ledger ()
  "Both SDK execution paths record failed process returns as failures."
  (let ((ogent-tool-registry (copy-tree ogent-tools-default-registry))
        (ogent-tool-require-approval nil) failures done)
    (cl-letf (((symbol-function 'ogent-ledger-record-tool-finish)
               (lambda (_call _data failure &rest _) (push failure failures))))
      (ogent-agent-call "bash" '(:command "exit 7"))
      (let ((process (ogent-agent-call-async "bash" '(:command "exit 8")
                                             (lambda (_) (setq done t)))))
        (while (and (process-live-p process) (not done)) (accept-process-output process 0.05))
        (accept-process-output nil 0.05))
      (should done)
      (should (= (length failures) 2))
      (should (cl-every #'stringp failures)))))

(ert-deftest ogent-agent-execution-batch-composes-read-tools ()
  "A single batch returns ordered typed results for independent read calls."
  (let* ((root (ogent-test--provision-store-directory 'tools))
         (file (ogent-agent-execution-tests--file root "data.txt" "needle\n"))
         (ogent-tool-registry (copy-tree ogent-tools-default-registry))
         (calls (list (list :tool "files" :args (list :pattern "*.txt" :path root))
                      (list :tool "search" :args (list :pattern "needle" :path root))
                      (list :tool "read" :args (list :file_path file))))
         (batch (json-parse-string (ogent-agent-batch calls 'json) :object-type 'plist)))
    (should (equal (plist-get batch :status) "ok"))
    (should (equal (plist-get batch :tool) "batch"))
    (should (= (length (plist-get (plist-get batch :data) :results)) 3))
    (should (equal (plist-get (aref (plist-get (plist-get batch :data) :results) 2) :tool) "read-file"))))

(ert-deftest ogent-agent-execution-batch-preflight-prevents-unsafe-prefix ()
  "An unsafe or invalid trailing call prevents any batch execution."
  (let ((ogent-tool-registry (copy-tree ogent-tools-default-registry))
        (ogent-tool-require-approval nil) (starts 0))
    (cl-letf (((symbol-function 'ogent-ledger-record-tool-start)
               (lambda (&rest _) (cl-incf starts))))
      (dolist (tail '((:tool "shell" :args (:command "touch marker"))
                      (:tool "read" :args (:file_path 2))))
        (let ((result (ogent-agent-batch (list '(:tool "files" :args (:pattern "*.el")) tail))))
          (should (equal (plist-get result :status) "error"))
          (should (= starts 0)))))))

(ert-deftest ogent-agent-execution-batch-continues-or-stops ()
  "Read failures are individually preserved, with explicit fail-fast counts."
  (let* ((root (ogent-test--provision-store-directory 'tools))
         (ogent-tool-registry (copy-tree ogent-tools-default-registry))
         (calls (list (list :tool "read" :args (list :file_path (expand-file-name "missing" root)))
                      (list :tool "files" :args (list :pattern "*.el" :path root)))))
    (should (= (plist-get (plist-get (ogent-agent-batch calls) :data) :completed) 2))
    (should (= (plist-get (plist-get (ogent-agent-batch calls nil t) :data) :completed) 1))
    (should (equal (plist-get (plist-get (ogent-agent-batch []) :data) :results) []))))

(ert-deftest ogent-agent-execution-discovery-exposes-real-call-shapes ()
  "Tool discovery advertises pagination, examples and actual async support."
  (let ((ogent-tool-registry (copy-tree ogent-tools-default-registry)))
    (let ((read (plist-get (ogent-agent-describe "read") :tool))
          (search (plist-get (ogent-agent-describe "search") :tool)))
      (should (member "column" (mapcar (lambda (arg) (plist-get arg :name))
                                       (append (plist-get read :call_arguments) nil))))
      (should (member "limit" (mapcar (lambda (arg) (plist-get arg :name))
                                      (append (plist-get search :call_arguments) nil))))
      (should (eq (plist-get search :async_sdk) t))
      (should (eq (plist-get search :async) :json-false))
      (should (> (length (plist-get read :examples)) 0)))))

(ert-deftest ogent-agent-execution-discovery-example-executes ()
  "The curated read example is executable against a project fixture."
  (let* ((root (ogent-test--provision-store-directory 'tools))
         (ogent-tools-project-root root)
         (ogent-tool-registry (copy-tree ogent-tools-default-registry)))
    (ogent-agent-execution-tests--file root "README.org" "example\n")
    (let* ((tool (plist-get (ogent-agent-describe "read_file") :tool))
           (result (eval (read (aref (plist-get tool :examples) 0)) t)))
      (should (equal (plist-get result :status) "ok"))
      (should (equal (plist-get (plist-get result :data) :content) "example")))))

(ert-deftest ogent-agent-execution-discovery-schema-and-purity ()
  "Descriptions and schemas serialize without running a tool or provider."
  (let ((ogent-tool-registry (copy-tree ogent-tools-default-registry)))
    (cl-letf (((symbol-function 'ogent-tool-execution-call)
               (lambda (&rest _) (ert-fail "Discovery executed a tool"))))
      (let ((schema (json-parse-string (ogent-agent-schema 'json) :object-type 'plist)))
        (should (equal (plist-get schema :type) "object"))
        (should (vectorp (plist-get schema :required)))
        (should (equal (plist-get (plist-get (plist-get schema :properties) :next) :type) "array")))
      (should (stringp (ogent-agent-describe "read" 'json)))
      (should (string-match-p "ogent-agent-next" (ogent-agent-guide)))
      (should-error (ogent-agent-describe "shll") :type 'user-error))))

(ert-deftest ogent-agent-execution-model-json-pages-and-cache-refresh ()
  "Model-facing JSON tools expose pagination and refresh on format changes."
  (let* ((root (ogent-test--provision-store-directory 'tools))
         (ogent-tools-project-root root)
         (ogent-tool-registry (copy-tree ogent-tools-default-registry))
         (ogent--tools-registered nil) (ogent--tool-specs-registered nil)
         (ogent--tool-formats-registered nil) (gptel--known-tools nil)
         (ogent-tools-result-format 'text) (constructed 0))
    (ogent-agent-execution-tests--file root "one.el" "")
    (ogent-agent-execution-tests--file root "two.el" "")
    (cl-letf (((symbol-function 'gptel-make-tool)
               (lambda (&rest args) (cl-incf constructed) args)))
      (let ((text (ogent-tool-get "glob")))
        (should (stringp (funcall (plist-get text :function) "*.el" root)))
        (should (= (length (plist-get text :args)) 2)))
      (let* ((ogent-tools-result-format 'json)
             (tool (ogent-tool-get "glob"))
             (data (json-parse-string (funcall (plist-get tool :function) "*.el" root 0 1)
                                      :object-type 'plist)))
        (should (= (length (plist-get tool :args)) 4))
        (should (equal (plist-get data :status) "ok"))
        (should (= (length (plist-get data :next)) 1))
        (should (= constructed 12))
        (ogent-tool-get "glob")
        (should (= constructed 12)))
      (ogent-tool-get "glob")
      (should (= constructed 18)))))

(ert-deftest ogent-agent-execution-model-stale-after-approval ()
  "Changing registry entries during approval cannot execute new functions."
  (dolist (format '(text json))
    (let* ((executed nil)
           (spec (list :name 'changing :confirm t :args nil :function (lambda () "original")))
           (ogent-tool-registry (list spec))
           (ogent-tool-require-approval t)
           (ogent-tool-allow-list nil) (ogent-tool--denied-tools nil)
           (wrapper (ogent-tool-execution-wrapper spec format)))
      (cl-letf (((symbol-function 'ogent-tool--prompt-approval)
                 (lambda (&rest _)
                   (setq ogent-tool-registry
                         (list (list :name 'changing :confirm t :args nil
                                     :function (lambda () (setq executed t) "replacement"))))
                   'approve)))
        (let ((result (funcall wrapper)))
          (should-not executed)
          (if (eq format 'json)
              (should (equal (plist-get (plist-get (json-parse-string result :object-type 'plist) :error) :code)
                             "unavailable"))
            (should (string-match-p "Tool unavailable:" result))))))))

(ert-deftest ogent-agent-execution-model-inplace-change-during-approval ()
  "Reject in-place function and effect changes made while approving a tool."
  (dolist (format '(text json))
    (let* ((executed nil)
           (spec (list :name 'changing :confirm t :args nil :function (lambda () "original")))
           (ogent-tool-registry (list spec))
           (ogent-tool-require-approval t)
           (ogent-tool-allow-list nil) (ogent-tool--denied-tools nil)
           (wrapper (ogent-tool-execution-wrapper spec format)))
      (cl-letf (((symbol-function 'ogent-tool--prompt-approval)
                 (lambda (&rest _)
                   (setf (plist-get spec :function) (lambda () (setq executed t)))
                   (setf (plist-get spec :effects) '((:kind network :risk critical)))
                   'approve)))
        (let ((result (funcall wrapper)))
          (should-not executed)
          (if (eq format 'json)
              (should (equal (plist-get (plist-get (json-parse-string result :object-type 'plist) :error) :code)
                             "unavailable"))
            (should (string-match-p "Tool unavailable:" result))))))))

(ert-deftest ogent-agent-execution-batch-inplace-effects-change ()
  "Refuse a preflighted read when an earlier call mutates its live effects."
  (let* ((executed nil)
         (later (list :name 'later :args nil :effects '((:kind read :target file :risk low))
                      :function (lambda () "safe")))
         (first (list :name 'first :args nil :effects '((:kind read :target file :risk low))
                      :function (lambda ()
                                  (setf (plist-get later :function) (lambda () (setq executed t)))
                                  (setf (plist-get later :effects) '((:kind write :target file :risk high)))
                                  "first")))
         (ogent-tool-registry (list first later))
         (ogent-tool-require-approval nil)
         (result (ogent-agent-batch '[(:tool "first" :args nil) (:tool "later" :args nil)])))
    (should-not executed)
    (should (equal (plist-get result :status) "partial"))
    (should (equal (plist-get (plist-get (aref (plist-get (plist-get result :data) :results) 1) :error) :code)
                   "unavailable"))))

(ert-deftest ogent-agent-execution-batch-freezes-calls-and-argument-strings ()
  "Keep preflighted names and argument values when earlier calls mutate input."
  (let* ((executed nil)
         (value (copy-sequence "safe"))
         (later-call (list :tool "later" :args (list :value value)))
         (schema '((:name "value" :type "string")))
         (later (list :name 'later :args schema :effects '((:kind read :target file :risk low))
                      :function #'identity))
         (write (list :name 'write-fixture :args schema :effects '((:kind write :target file :risk high))
                      :function (lambda (_) (setq executed t))))
         (first (list :name 'first :args nil :effects '((:kind read :target file :risk low))
                      :function (lambda ()
                                  (setf (plist-get later-call :tool) "write-fixture")
                                  (aset value 0 ?X)
                                  "first")))
         (ogent-tool-registry (list first later write))
         (ogent-tool-require-approval nil)
         (result (ogent-agent-batch (list (list :tool "first" :args nil) later-call))))
    (should-not executed)
    (should (equal (plist-get result :status) "ok"))
    (should (equal (plist-get (plist-get (aref (plist-get (plist-get result :data) :results) 1) :data) :value)
                   "safe"))))

(ert-deftest ogent-agent-execution-batch-freezes-canonical-alias-target ()
  "Keep the resolved tool when an earlier call registers a colliding alias name."
  (let* ((executed nil)
         (later (list :name 'later :aliases '["alias"] :args nil
                      :effects '((:kind read :target file :risk low)) :function (lambda () "read")))
         (first (list :name 'first :args nil :effects '((:kind read :target file :risk low))
                      :function (lambda ()
                                  (push (list :name 'alias :args nil
                                              :effects '((:kind write :target file :risk high))
                                              :function (lambda () (setq executed t)))
                                        ogent-tool-registry)
                                  "first")))
         (ogent-tool-registry (list first later))
         (ogent-tool-require-approval nil)
         (result (ogent-agent-batch '[(:tool "first" :args nil) (:tool "alias" :args nil)])))
    (should-not executed)
    (should (equal (plist-get result :status) "ok"))
    (should (equal (plist-get (aref (plist-get (plist-get result :data) :results) 1) :tool) "later"))))

(ert-deftest ogent-agent-execution-model-freezes-metadata-strings ()
  "Refuse in-place effect string changes during approval in both result modes."
  (dolist (format '(text json))
    (let* ((executed nil) (target (copy-sequence "safe"))
           (spec (list :name 'changing :confirm t :args nil
                       :effects (list (list :kind 'read :target target :risk 'low))
                       :function (lambda () (setq executed t))))
           (ogent-tool-registry (list spec))
           (ogent-tool-require-approval t)
           (ogent-tool-allow-list nil) (ogent-tool--denied-tools nil)
           (wrapper (ogent-tool-execution-wrapper spec format)))
      (cl-letf (((symbol-function 'ogent-tool--prompt-approval)
                 (lambda (&rest _) (aset target 0 ?X) 'approve)))
        (let ((result (funcall wrapper)))
          (should-not executed)
          (if (eq format 'json)
              (should (equal (plist-get (plist-get (json-parse-string result :object-type 'plist) :error) :code)
                             "unavailable"))
            (should (string-match-p "Tool unavailable:" result))))))))

(ert-deftest ogent-agent-execution-model-freezes-argument-strings ()
  "Keep validated input strings when external input changes during approval."
  (dolist (format '(text json))
    (let* ((value (copy-sequence "safe"))
           (spec (list :name 'echo :confirm t :args '((:name "value" :type "string"))
                       :function #'identity))
           (ogent-tool-registry (list spec))
           (ogent-tool-require-approval t)
           (ogent-tool-allow-list nil) (ogent-tool--denied-tools nil)
           (wrapper (ogent-tool-execution-wrapper spec format)))
      (cl-letf (((symbol-function 'ogent-tool--prompt-approval)
                 (lambda (&rest _) (aset value 0 ?X) 'approve)))
        (let ((result (funcall wrapper value)))
          (should (equal (if (eq format 'json)
                             (plist-get (plist-get (json-parse-string result :object-type 'plist) :data) :value)
                           result)
                         "safe")))))))

(ert-deftest ogent-agent-execution-model-freezes-object-arguments ()
  "Keep approved object values even when the original table changes."
  (dolist (format '(text json))
    (let* ((payload (make-hash-table :test #'equal))
           (properties (let ((table (make-hash-table :test #'equal)))
                         (puthash "selection" '(:type "string") table)
                         table))
           (spec (list :name 'object-reader :confirm t
                       :args (list (list :name "payload" :type "object" :properties properties))
                       :function (lambda (object) (gethash "selection" object))))
           (ogent-tool-registry (list spec))
           (ogent-tool-require-approval t)
           (ogent-tool-allow-list nil) (ogent-tool--denied-tools nil)
           (wrapper (ogent-tool-execution-wrapper spec format)))
      (puthash "selection" "original" payload)
      (cl-letf (((symbol-function 'ogent-tool--prompt-approval)
                 (lambda (&rest _) (puthash "selection" "changed" payload) 'approve)))
        (let ((result (funcall wrapper payload)))
          (should (equal (if (eq format 'json)
                             (plist-get (plist-get (json-parse-string result :object-type 'plist) :data) :value)
                           result)
                         "original")))))))

(ert-deftest ogent-agent-execution-batch-freezes-nested-object-values ()
  "Keep a later object's preflight value when an earlier read mutates input."
  (let* ((payload (make-hash-table :test #'equal))
         (nested (make-hash-table :test #'equal))
         (first (list :name 'first :args nil :effects '((:kind read :target file :risk low))
                      :function (lambda () (puthash "selection" "changed" nested) "first")))
         (later (list :name 'later :args '((:name "payload" :type "object"))
                      :effects '((:kind read :target file :risk low))
                      :function (lambda (object) (gethash "selection" (gethash "nested" object)))))
         (ogent-tool-registry (list first later))
         (ogent-tool-require-approval nil))
    (puthash "selection" "original" nested)
    (puthash "nested" nested payload)
    (let ((result (ogent-agent-batch (list (list :tool "first" :args nil)
                                           (list :tool "later" :args (list :payload payload))))))
      (should (equal (plist-get result :status) "ok"))
      (should (equal (plist-get (plist-get (aref (plist-get (plist-get result :data) :results) 1) :data) :value)
                     "original")))))

(ert-deftest ogent-agent-execution-model-detects-object-schema-mutation ()
  "Reject object metadata changed in place during approval."
  (let* ((properties (make-hash-table :test #'equal))
         executed
         (spec (list :name 'changing :confirm t :args nil :metadata properties
                     :function (lambda () (setq executed t))))
         (ogent-tool-registry (list spec))
         (ogent-tool-require-approval t)
         (ogent-tool-allow-list nil) (ogent-tool--denied-tools nil)
         (wrapper (ogent-tool-execution-wrapper spec 'json)))
    (cl-letf (((symbol-function 'ogent-tool--prompt-approval)
               (lambda (&rest _) (puthash "selection" "changed" properties) 'approve)))
      (let ((result (json-parse-string (funcall wrapper) :object-type 'plist)))
        (should-not executed)
        (should (equal (plist-get (plist-get result :error) :code) "unavailable"))))))

(ert-deftest ogent-agent-execution-model-refreshes-object-schema-cache ()
  "Refresh model objects when nested schema tables change without sharing them."
  (let* ((properties (make-hash-table :test #'equal))
         (spec (list :name 'object-reader :description "Read an object"
                     :args (list (list :name "payload" :type "object" :properties properties))
                     :function #'identity))
         (ogent-tool-registry (list spec))
         (ogent--tools-registered nil) (ogent--tool-specs-registered nil)
         (ogent--tool-formats-registered nil) (gptel--known-tools nil)
         (ogent-tools-result-format 'json) (constructed 0))
    (puthash "selection" '(:type "string") properties)
    (cl-letf (((symbol-function 'gptel-make-tool)
               (lambda (&rest args) (cl-incf constructed) args)))
      (let ((first (ogent-tool-get "object-reader")))
        (should (eq first (ogent-tool-get "object-reader")))
        (puthash "selection" '(:type "integer") properties)
        (let ((second (ogent-tool-get "object-reader")))
          (should-not (eq first second))
          (should (= constructed 2))
          (should (equal (gethash "selection" (plist-get (car (plist-get first :args)) :properties))
                         '(:type "string")))
          (should (equal (gethash "selection" (plist-get (car (plist-get second :args)) :properties))
                         '(:type "integer"))))))))

(ert-deftest ogent-agent-execution-model-json-async-callback ()
  "Gptel callback-first calls retain JSON and exactly one terminal callback."
  (let* ((spec (list :name 'async-fixture :async t :args '((:name "value" :type "string"))
                     :function (lambda (value callback) (funcall callback value) (funcall callback "again"))))
         (ogent-tool-registry (list spec))
         (ogent-tool-require-approval nil) (calls 0) result)
    (funcall (ogent-tool-execution-wrapper spec 'json)
             (lambda (json) (cl-incf calls) (setq result json)) "payload")
    (should (= calls 1))
    (should (equal (plist-get (plist-get (json-parse-string result :object-type 'plist) :data) :value) "payload"))))

(ert-deftest ogent-agent-execution-json-unsupported-path-delivers-error ()
  "Raw-byte filenames produce safe typed errors including async JSON calls."
  (let* ((root (ogent-test--provision-store-directory 'tools))
         (file (concat root "/" (unibyte-string 255) ".txt"))
         (ogent-tool-registry (copy-tree ogent-tools-default-registry))
         result (calls 0))
    (with-temp-file file (insert "contents"))
    (let ((sync (json-parse-string (ogent-agent-call "read" (list :file_path file) 'json)
                                   :object-type 'plist)))
      (should (equal (plist-get (plist-get sync :error) :code) "unsupported_output")))
    (ogent-agent-call-async "read" (list :file_path file)
                            (lambda (data) (cl-incf calls) (setq result data)) 'json)
    (should (= calls 1))
    (should (equal (plist-get (plist-get (json-parse-string result :object-type 'plist) :error) :code)
                   "unsupported_output"))))

(ert-deftest ogent-agent-execution-json-unsupported-extension-callback-once ()
  "Unserializable extension results still deliver one JSON error callback."
  (let* ((spec (list :name 'bad-json :async t :args nil
                     :function (lambda (callback) (funcall callback (unibyte-string 255)))))
         (ogent-tool-registry (list spec))
         (ogent-tool-require-approval nil) (calls 0) result)
    (dolist (invoke (list (lambda (callback) (ogent-agent-call-async "bad-json" nil callback 'json))
                          (lambda (callback) (funcall (ogent-tool-execution-wrapper spec 'json) callback))))
      (setq calls 0 result nil)
      (funcall invoke (lambda (data) (cl-incf calls) (setq result data)))
      (should (= calls 1))
      (should (equal (plist-get (plist-get (json-parse-string result :object-type 'plist) :error) :code)
                     "unsupported_output")))))

(ert-deftest ogent-agent-execution-named-call-and-json ()
  "Named calls preserve values and return independently parseable JSON."
  (let ((ogent-tool-registry
         (list (list :name 'echo :function #'identity
                     :args '((:name "value" :type "string")))))
        (ogent-tool-require-approval nil))
    (let ((result (json-parse-string
                   (ogent-agent-call "echo" '(:value "Tool error: literal") 'json)
                   :object-type 'plist)))
      (should (equal (plist-get result :status) "ok"))
      (should (equal (plist-get (plist-get result :data) :value) "Tool error: literal"))
      (should (equal (plist-get result :contract_version) "1")))))

(ert-deftest ogent-agent-execution-validates-before-policy ()
  "Invalid arguments and formats cannot reach approval or execution."
  (let ((ogent-tool-registry
         (list (list :name 'echo :function #'identity
                     :args '((:name "value" :type "string")))))
        (calls 0))
    (cl-letf (((symbol-function 'ogent-tool-approval-check)
               (lambda (&rest _) (cl-incf calls) 'approved)))
      (should (equal (plist-get (plist-get (ogent-agent-call "echo" '(:value 5)) :error) :code)
                     "invalid_arguments"))
      (should-error (ogent-agent-call "echo" '(:value "x") 'yaml) :type 'user-error)
      (should (= calls 0)))))

(ert-deftest ogent-agent-execution-denial-and-approval-required ()
  "Denied and approval-required calls cannot mutate files or prompt."
  (let ((ogent-tool-registry (copy-tree ogent-tools-default-registry))
        (ogent-tool-allow-list nil)
        (ogent-tool--denied-tools nil)
        (ogent-tool-require-approval t)
        (root (ogent-test--provision-store-directory 'tools)))
    (cl-letf (((symbol-function 'ogent-tool--prompt-approval)
               (lambda (&rest _) (ert-fail "Programmatic calls must not prompt"))))
      (let ((file (expand-file-name "new.txt" root)))
        (should (equal (plist-get (ogent-agent-call "write_file" (list :file_path file :content "new")) :status)
                       "approval_required"))
        (should-not (file-exists-p file))
        (let ((ogent-tool--denied-tools '("write-file")))
          (should (equal (plist-get (ogent-agent-call "write_file" (list :file_path file :content "new")) :status)
                         "denied")))
        (should-not (file-exists-p file))))))

(ert-deftest ogent-agent-execution-failures-recorded ()
  "An execution failure is typed and records a failed ledger terminal."
  (let ((ogent-tool-registry
         (list (list :name 'fail :function (lambda () (user-error "Choose an existing file"))
                     :args nil)))
        (ogent-tool-require-approval nil)
        recorded)
    (cl-letf (((symbol-function 'ogent-ledger-record-tool-finish)
               (lambda (_call _result failure &rest _) (setq recorded failure))))
      (let ((result (ogent-agent-call "fail" nil)))
        (should (equal (plist-get result :status) "error"))
        (should (equal (plist-get (plist-get result :error) :code) "execution_failed"))
        (should (equal recorded "Choose an existing file"))))))

(provide 'ogent-agent-execution-tests)
;;; ogent-agent-execution-tests.el ends here
