;;; search_probe.el --- Review-only cross-engine search probe -*- lexical-binding: t; -*-
(require 'ogent-tool-process)
(let* ((root (expand-file-name
              "agent_ergonomics_audit/audit/evidence/pass_3/review_round7/search-probe/"
              "/work/"))
       (ogent-test-tripwire-allowed-roots (cons root ogent-test-tripwire-allowed-roots))
       (real-find (symbol-function 'executable-find))
       (rg "/tmp/ogent-test-rg")
       (text "before\nneedle one\nmiddle\nneedle two\nafter\n")
       (ogent-tools-max-output-chars 50000)
       (ogent-tools-grep-timeout 10)
       expected first-engine)
  (make-directory root t)
  (dotimes (index 132)
    (with-temp-file (expand-file-name (format "%03d.txt" index) root) (insert text)))
  (with-temp-file (expand-file-name "odd\n:99 ü.txt" root) (insert text))
  (with-temp-file (expand-file-name "binary.txt" root)
    (insert "needle first\n" (make-string 100000 ?x) "\0needle last\n"))
  (make-directory (expand-file-name ".git" root) t)
  (with-temp-file (expand-file-name ".git/private.txt" root) (insert text))
  (unless (file-symlink-p (expand-file-name "linked.txt" root))
    (make-symbolic-link "000.txt" (expand-file-name "linked.txt" root)))
  (unless (file-symlink-p (expand-file-name "loop" root))
    (make-symbolic-link "." (expand-file-name "loop" root)))
  (dolist (engine '(ripgrep gnu-grep))
    (cl-letf (((symbol-function 'executable-find)
               (lambda (name &optional remote)
                 (if (equal name "rg")
                     (when (eq engine 'ripgrep) rg)
                   (funcall real-find name remote)))))
      (let* ((page (ogent-tool-process-grep "needle" root "*.txt" 1 0 200))
             (matches (plist-get page :matches))
             (last (ogent-tool-process-grep "needle" root "*.txt" 1 200 200)))
        (cl-assert (= (plist-get page :total_matches) 268))
        (cl-assert (= (length matches) 200))
        (cl-assert (eq (plist-get page :has_more) t))
        (cl-assert (= (length (plist-get last :matches)) 68))
        (cl-assert (eq (plist-get last :has_more) :json-false))
        (cl-assert (equal (plist-get page :snapshot) (plist-get last :snapshot)))
        (cl-assert (equal (plist-get (aref matches 0) :text) "needle one"))
        (cl-assert (equal (plist-get (aref (plist-get (aref matches 0) :context_before) 0) :text)
                          "before"))
        (cl-assert (equal (plist-get (aref (plist-get (aref matches 0) :context_after) 0) :text)
                          "middle"))
        (setq expected (append (append matches nil) (append (plist-get last :matches) nil)))
        (if first-engine (cl-assert (equal expected first-engine))
          (setq first-engine expected))
        (princ (format "%S total=%S pages=%d+%d snapshots=stable context=correct binary/git/loop=excluded file-link=preserved\n"
                       engine (plist-get page :total_matches) (length matches)
                       (length (plist-get last :matches)))))))
  (princ "cross-engine match objects are identical\n"))
