;;; overlap-ledger-probe.el --- Independent ledger ownership check -*- lexical-binding: t; -*-

(require 'ogent-agent)
(require 'ogent-ui-toolcalls)

(ert-deftest ogent-round9-overlapping-ledgers-freeze-file-and-preserve-callback-context ()
  "Keep overlapping native/model calls at their own start destinations."
  (let* ((origin-a (ogent-test--provision-store-directory 'round9-ledger))
         (origin-b (ogent-test--provision-store-directory 'round9-ledger))
         (ambient (ogent-test--provision-store-directory 'round9-ledger))
         (file-a (expand-file-name "ledger-a.org" origin-a))
         (file-b (expand-file-name "ledger-b.org" origin-b))
         (ogent-ledger-enabled t)
         (ogent-ledger-file (copy-sequence file-a))
         (ogent-tool-require-approval nil)
         pending delivered
         (spec (list :name 'overlap :async t
                     :args '((:name "tag" :type "string"))
                     :result-function #'ignore
                     :function (lambda (tag complete)
                                 (push (cons tag complete) pending))))
         (ogent-tool-registry (list spec))
         (observe (lambda (result)
                    (should (equal default-directory ambient))
                    (should-not ogent-ledger-enabled)
                    (should (equal ogent-ledger-file "future.org"))
                    (when (stringp result)
                      (setq result (json-parse-string result :object-type 'plist)))
                    (push result delivered))))
    (let ((default-directory origin-a))
      (ogent-agent-call-async "overlap" '(:tag "A") observe))
    (should (file-exists-p file-a))
    ;; Destructively change the configuration string after the call captured it.
    (aset ogent-ledger-file (- (length ogent-ledger-file) 5) ?x)
    (let ((default-directory origin-b))
      (setq ogent-ledger-file "ledger-b.org")
      (funcall (ogent-tool-execution-wrapper spec 'json) observe "B"))
    (should (file-exists-p file-b))
    (setq ogent-ledger-enabled nil ogent-ledger-file "future.org")
    (let ((default-directory ambient))
      (funcall (cdr (assoc "B" pending)) '(:value "B"))
      (funcall (cdr (assoc "A" pending)) '(:value "A"))
      (funcall (cdr (assoc "A" pending)) '(:value "duplicate"))
      (should (equal default-directory ambient))
      (should-not ogent-ledger-enabled)
      (should (equal ogent-ledger-file "future.org")))
    (should (= (length delivered) 2))
    (should (equal (mapcar (lambda (result) (plist-get result :status)) delivered)
                   '("ok" "ok")))
    (should (equal (mapcar (lambda (result) (plist-get (plist-get result :data) :value)) delivered)
                   '("A" "B")))
    (dolist (pair (list (cons file-a "A") (cons file-b "B")))
      (with-temp-buffer
        (insert-file-contents (car pair))
        (should (= (count-matches "^:OGENT_LEDGER_TYPE: tool-start$" (point-min) (point-max)) 1))
        (should (= (count-matches "^:OGENT_LEDGER_TYPE: tool-finish$" (point-min) (point-max)) 1))
        (should (= (count-matches (concat ":tag \"" (cdr pair) "\"") (point-min) (point-max)) 2))
        (should-not (string-match-p "duplicate" (buffer-string)))))
    (dolist (directory (list origin-a origin-b ambient))
      (should-not (file-exists-p (expand-file-name "future.org" directory))))
    (should-not (file-exists-p (expand-file-name "ledger-b.org" ambient)))
    (should-not (file-exists-p (expand-file-name "ledger-x.org" origin-a)))))

(ert-run-tests-batch-and-exit "^ogent-round9-")
