;;; doctor-hint-probe.el --- Verify the doctor correction example -*- lexical-binding: t; -*-

(require 'ogent-doctor)
(dolist (style '(curve straight grave))
  (let ((text-quoting-style style)
        (called nil)
        hint correction code output)
    (let ((doc (documentation 'ogent-doctor-batch)))
      (unless (string-match "(ogent-doctor-batch nil (quote json))" doc)
        (error "Public doctor docstring lacks a valid JSON example: %S" doc))
      (let ((example (match-string 0 doc)))
        (unless (equal (read example) '(ogent-doctor-batch nil (quote json)))
          (error "Public doctor example is not a valid JSON call"))
        (princ (format "style=%S docstring-example=%S\n" style example))))
    (cl-letf (((symbol-function 'ogent-doctor-run)
               (lambda (&optional opt-in)
                 (unless (null opt-in) (error "Hint enabled opt-in probes"))
                 (setq called t)
                 '((:id fixture :label "Fixture" :category environment
                         :status ok :detail "local fixture")))))
      (setq hint (condition-case err
                     (ogent-doctor-batch t 'jsno)
                   (user-error (error-message-string err))))
      (when called (error "Invalid format ran diagnostics"))
      ;; Extract and read the actual captured advice, rather than reading a
      ;; predefined expected string that could hide quote substitution.
      (unless (string-match "(ogent-doctor-batch" hint)
        (error "Captured hint lacks a correction expression: %S" hint))
      (setq correction (substring hint (match-beginning 0)))
      (let* ((parsed (read-from-string correction))
             (form (car parsed))
             (remaining (substring correction (cdr parsed))))
        (unless (and (equal form '(ogent-doctor-batch nil (quote json)))
                     (string-empty-p (string-trim remaining)))
          (error "Captured correction is not a valid doctor JSON call: %S" correction))
        (setq output (with-output-to-string (setq code (eval form)))))
      (unless (and called (zerop code)
                   (equal "1" (plist-get (json-parse-string output :object-type 'plist)
                                         :contract_version)))
        (error "Pasted correction did not produce valid doctor JSON"))
      (princ (format "style=%S captured-hint=%S\nactual-correction=%S\npaste-result=%S\nexit-code=%d\nverdict=CLEAN\n"
                     style hint correction output code)))))
