;;; boundary-probe.el --- Independent round 6 checks -*- lexical-binding: t; -*-
(require 'ogent-test-helper)
(require 'ogent-agent)
(require 'ogent-tool-results)
(require 'ogent-tool-process)
(require 'ogent-ui-toolcalls)

(defun review6--write (directory name content)
  (let ((path (expand-file-name name directory)))
    (make-directory (file-name-directory path) t)
    (let ((coding-system-for-write 'utf-8-unix))
      (with-temp-file path (insert content)))
    path))

(ert-deftest review6-glob-continuation-keeps-original-project ()
  (let* ((directory (ogent-test--provision-store-directory 'tools))
         (ogent-tools-project-root directory)
         (ogent-tool-registry (copy-tree ogent-tools-default-registry)))
    (review6--write directory "a.el" "a")
    (review6--write directory "b.el" "b")
    (review6--write directory "elsewhere/c.el" "c")
    (let* ((first (ogent-agent-call "files" '(:pattern "*.el" :limit 1) 'json))
           (ogent-tools-project-root (expand-file-name "elsewhere" directory))
           (second (ogent-agent-next first 'json))
           (parsed (json-parse-string second :object-type 'plist)))
      (should (equal (plist-get parsed :status) "ok"))
      (should (equal (plist-get (aref (plist-get (plist-get parsed :data) :files) 0) :path)
                     (expand-file-name "b.el" directory)))
      (should (equal (plist-get (ogent-agent-next parsed) :status) "done")))))

(ert-deftest review6-search-continued-page-retains-identifiers-under-zero-budget ()
  (let* ((directory (ogent-test--provision-store-directory 'tools))
         (ogent-tools-project-root directory)
         (ogent-tool-registry (copy-tree ogent-tools-default-registry))
         (ogent-tools-max-output-chars 0)
         (find-executable (symbol-function 'executable-find)))
    (review6--write directory "left.txt" "needle\nneedle\nneedle\n")
    (review6--write directory "right.txt" "needle\nneedle\n")
    (dolist (engine '(gnu ripgrep))
      (cl-letf (((symbol-function 'executable-find)
                 (lambda (name &optional remote)
                   (if (equal name "rg")
                       (when (eq engine 'ripgrep) (getenv "OGENT_PROCESS_TEST_RG"))
                     (funcall find-executable name remote)))))
        (let ((result (ogent-agent-call "search" '(:pattern "needle" :limit 2)))
              (count 0) (pages 0))
          (while (equal (plist-get result :status) "ok")
            (let ((data (plist-get result :data)))
              (should (= (plist-get data :total_matches) 5))
              (cl-incf pages)
              (dolist (match (append (plist-get data :matches) nil))
                (should (file-name-absolute-p (plist-get match :path)))
                (should (> (plist-get match :line) 0))
                (should (equal (plist-get match :text) ""))
                (should (eq (plist-get match :truncated) t))
                (cl-incf count)))
            (setq result (ogent-agent-next result)))
          (should (= count 5))
          (should (= pages 3))
          (should (equal (plist-get result :status) "done")))))))

(ert-deftest review6-continuation-refuses-change-outside-first-page ()
  (let* ((directory (ogent-test--provision-store-directory 'tools))
         (ogent-tools-project-root directory)
         (ogent-tool-registry (copy-tree ogent-tools-default-registry)))
    (review6--write directory "file.txt" "first\nlast\n")
    (let ((result (ogent-agent-call "cat" '(:file_path "file.txt" :limit 1))))
      (review6--write directory "file.txt" "first\nchanged\n")
      (let ((next (ogent-agent-next result)))
        (should (equal (plist-get next :status) "error"))
        (should (equal (plist-get (plist-get next :error) :code) "snapshot_changed")))))
  (let* ((directory (ogent-test--provision-store-directory 'tools))
         (ogent-tools-project-root directory)
         (ogent-tool-registry (copy-tree ogent-tools-default-registry)))
    (review6--write directory "first.txt" "needle\n")
    (review6--write directory "last.txt" "needle\n")
    (let ((result (ogent-agent-call "search" '(:pattern "needle" :limit 1))))
      (review6--write directory "last.txt" "needle changed\n")
      (let ((next (ogent-agent-next result)))
        (should (equal (plist-get next :status) "error"))
        (should (equal (plist-get (plist-get next :error) :code) "snapshot_changed"))))))

(ert-deftest review6-process-timeout-delivers-both-channels-once ()
  (let* ((directory (ogent-test--provision-store-directory 'tools))
         (ogent-tools-project-root directory)
         (ogent-tool-registry (copy-tree ogent-tools-default-registry))
         (ogent-tool-allow-list '("bash"))
         (ogent-tool--denied-tools nil)
         (started (float-time))
         (deliveries 0) terminal)
    (ogent-agent-call-async
     "shell" '(:command "printf beginning; printf diagnostic >&2; sleep 5" :timeout 0.2)
     (lambda (result) (cl-incf deliveries) (setq terminal result)))
    (while (and (not terminal) (< (- (float-time) started) 2))
      (accept-process-output nil 0.02))
    (should (= deliveries 1))
    (should (equal (plist-get (plist-get terminal :error) :code) "timeout"))
    (should (equal (plist-get (plist-get terminal :data) :stdout) "beginning"))
    (should (equal (plist-get (plist-get terminal :data) :stderr) "diagnostic"))
    (should-not ogent-tools--active-processes)))

(let* ((directory (ogent-test--provision-store-directory 'tools))
       (ogent-tools-project-root directory)
       (find-executable (symbol-function 'executable-find)))
  (review6--write directory "source.txt" "needle\n")
  (make-symbolic-link (expand-file-name "source.txt" directory)
                     (expand-file-name "link.txt" directory))
  (dolist (engine '(gnu ripgrep))
    (cl-letf (((symbol-function 'executable-find)
               (lambda (name &optional remote)
                 (if (equal name "rg")
                     (when (eq engine 'ripgrep) (getenv "OGENT_PROCESS_TEST_RG"))
                   (funcall find-executable name remote)))))
      (dolist (filter '(nil "*.txt" "link.txt" "l?nk.txt" "l[ia]nk.txt"))
        (princ (format "symlink-directory-%s filter=%S matches=%S\n" engine filter
                       (mapcar (lambda (match) (file-name-nondirectory (plist-get match :path)))
                               (append (plist-get (ogent-tool-process-grep "needle" directory filter)
                                                  :matches) nil))))))))

(ert-run-tests-batch-and-exit "^review6-")
