;;; boundary.el --- Independent reflected string checks -*- lexical-binding: t; -*-
(require 'ogent-agent)
(require 'ogent-tool-process)
(require 'ogent-tool-results)

(defun review14--decode (value)
  "Decode contract VALUE when it is a JSON string."
  (if (stringp value)
      (json-parse-string value :object-type 'plist :false-object :json-false :null-object :json-null)
    value))

(defun review14--call (name args format async)
  "Return NAME result for ARGS, FORMAT and optional ASYNC delivery."
  (if (not async) (ogent-agent-call name args format)
    (let ((calls 0) result process)
      (setq process (ogent-agent-call-async name args
                                          (lambda (value) (cl-incf calls) (setq result value)) format))
      (let ((deadline (+ (float-time) 10)))
        (while (and (= calls 0) (< (float-time) deadline)) (accept-process-output nil 0.01)))
      (should (= calls 1))
      (when process (should-not (process-live-p process)))
      result)))

(defun review14--representable (result)
  "Assert RESULT survives contract JSON serialization exactly."
  (should (equal result (review14--decode (json-serialize result :false-object :json-false :null-object :json-null)))))

(ert-deftest review14-reflected-raw-strings-empty-queries ()
  "Reject raw built-in query strings independently of empty candidate selection."
  (let* ((root (make-temp-file "review14-empty-" t))
         (raw (decode-coding-string (unibyte-string 252) 'utf-8-unix))
         (ogent-tool-registry (copy-tree ogent-tools-default-registry))
         (ogent-ledger-enabled nil)
         (ogent-tools-project-root root))
    (unwind-protect
        (dolist (entry (list (list "files" (list :pattern (concat "[a" raw "]*.el")))
                            (list "search" (list :pattern (concat "[n" raw "]eedle")))
                            (list "search" (list :pattern "needle" :glob_filter (concat "[a" raw "]*.el")))
                            (list "read" (list :file_path (concat root "/" raw)))))
          (dolist (format '(plist json))
            (dolist (async '(nil t))
              (let ((result (review14--decode (review14--call (car entry) (cadr entry) format async))))
                (review14--representable result)
                (should (equal (plist-get result :tool) (if (equal (car entry) "files") "glob"
                                                       (if (equal (car entry) "search") "grep" "read-file"))))
                (should (equal (plist-get result :status) "error"))
                (should (equal (plist-get (plist-get result :error) :code) "unsupported_output"))
                (should (zerop (length (plist-get result :next))))))))
      (delete-directory root t))))

(ert-deftest review14-unicode-empty-and-continuation-roundtrip ()
  "Retain Unicode strings through all read-only formats, pages and completion."
  (let* ((root (make-temp-file "review14-λ-" t))
         (file (expand-file-name "日本😀\t\n.el" root))
         (ogent-tool-registry (copy-tree ogent-tools-default-registry))
         (ogent-ledger-enabled nil)
         (ogent-tools-project-root root)
         (ogent-tools-max-output-chars 5))
    (unwind-protect
        (progn
          (with-temp-file file (insert "λ😀日本é\nλ😀日本é\n"))
          (with-temp-file (expand-file-name "é.el" root) (insert "λ😀日本é\n"))
          (dolist (entry (list (list "files" '(:pattern "**/*.el" :limit 1))
                              (list "search" '(:pattern "λ" :glob_filter "**/*.el" :limit 1))
                              (list "read" (list :file_path file :limit 1))
                              (list "files" '(:pattern "**/never-😀.*"))
                              (list "search" '(:pattern "λ" :glob_filter "never-😀.*"))))
            (dolist (format '(plist json))
              (dolist (async '(nil t))
                (let* ((value (review14--call (car entry) (cadr entry) format async))
                       (result (review14--decode value))
                       (pages 0))
                  (should (equal (plist-get result :status) "ok"))
                  (review14--representable result)
                  (while (> (length (plist-get result :next)) 0)
                    (let* ((next (aref (plist-get result :next) 0))
                           (args (plist-get next :args)))
                      (should (file-name-absolute-p (or (plist-get args :path) (plist-get args :file_path))))
                      (should (equal (cadr (nth 2 (read (plist-get next :call)))) args)))
                    (setq value (ogent-agent-next value format) result (review14--decode value))
                    (should (equal (plist-get result :status) "ok"))
                    (review14--representable result)
                    (cl-incf pages)
                    (should (< pages 10)))
                  (should (equal (plist-get (review14--decode (ogent-agent-next value format)) :status) "done")))))))
      (delete-directory root t))))

(ert-deftest review14-actual-gptel-search-continuation-wire ()
  "Use actual gptel result processing and nested encoding for search pages."
  (let* ((root (make-temp-file "review14-wire-λ-" t))
         (raw (decode-coding-string (unibyte-string 251) 'utf-8-unix))
         (ogent-tool-registry (copy-tree ogent-tools-default-registry))
         (ogent-tools-result-format 'json) (ogent-ledger-enabled nil)
         (ogent--tools-registered nil) (ogent--tool-specs-registered nil)
         (ogent--tool-formats-registered nil) (gptel--known-tools nil)
         (backend (gptel-make-openai "review14-offline" :host "offline.invalid" :key "unused" :models '(local))))
    (unwind-protect
        (progn
          (with-temp-file (expand-file-name "é😀.el" root) (insert "λ\nλ\n"))
          (dolist (filter (list "*.el" (concat "[é" raw "]*.el")))
            (let* ((tool (ogent-tool-get "search"))
                   (value (funcall (gptel-tool-function tool) "λ" root filter 0 0 1))
                   (completed (list :id "complete" :name "grep" :args (list :pattern "λ" :path root :glob_filter filter)))
                   (pending (list :id "hold-offline" :name "grep"))
                   (fsm (gptel-make-fsm :info (list :backend backend :tool-use (list completed pending)))))
              (gptel--process-tool-call fsm tool completed value)
              (should-not (plist-get pending :result))
              (let* ((messages (gptel--parse-tool-results backend (list completed)))
                     (wire (gptel--json-encode (list :messages (vconcat messages))))
                     (parsed (review14--decode wire))
                     (content (plist-get (aref (plist-get parsed :messages) 0) :content))
                     (result (review14--decode content)))
                (should (equal content value))
                (review14--representable result)
                (if (equal filter "*.el")
                    (progn
                      (should (equal (plist-get result :status) "ok"))
                      (should (= (length (plist-get result :next)) 1))
                      (should (equal (plist-get (review14--decode (ogent-agent-next content 'json)) :status) "ok")))
                  (should (equal (plist-get (plist-get result :error) :code) "unsupported_output")))))))
      (delete-directory root t))))

(ert-deftest review14-native-extension-value-is-preserved ()
  "Keep native extension objects while JSON produces its documented fallback."
  (let* ((object (generate-new-buffer " *review14-native*"))
         (ogent-tool-registry (list (list :name 'review14-native :function (lambda () object)
                                         :args nil :effects '((:kind read :risk low)))))
         (ogent-ledger-enabled nil))
    (unwind-protect
        (progn
          (should (eq (plist-get (plist-get (ogent-agent-call "review14-native" nil) :data) :value) object))
          (should (equal (plist-get (plist-get (review14--decode (ogent-agent-call "review14-native" nil 'json)) :error) :code)
                         "unsupported_output")))
      (kill-buffer object))))
