;;; boundary-probe.el --- Frozen file and callback boundaries -*- lexical-binding: t; -*-
(require 'ogent-agent)
(require 'ogent-tool-process)
(let* ((directory (ogent-test--provision-store-directory 'tools))
       (file (concat directory "/" (unibyte-string 255) ".txt"))
       (ogent-tool-registry (copy-tree ogent-tools-default-registry))
       (ogent-tools-project-root directory))
  (with-temp-file file (insert "text\n"))
  (princ (format "file=%S exists=%S multibyte=%S listing=%S\n" file (file-exists-p file) (multibyte-string-p file) (directory-files directory)))
  (princ (format "read-plist=%S\n" (ogent-agent-call "read" (list :file_path file))))
  (let ((calls 0))
    (condition-case err
        (ogent-agent-call-async "read" (list :file_path file)
                                (lambda (_) (cl-incf calls)) 'json)
      (error (princ (format "read-async-json-error=%S\n" err))))
    (princ (format "read-async-json-callbacks=%d\n" calls)))
  (dolist (call (list (list "read" (list :file_path file))
                     (list "files" (list :pattern "*" :path directory))))
    (condition-case err
        (princ (format "%s-json=%s" (car call) (ogent-agent-call (car call) (cadr call) 'json)))
      (error (princ (format "%s-json-error=%S\n" (car call) err))))))
(let* ((callbacks 0)
       (spec (list :name 'bad-result :async t :args nil
                   :function (lambda (callback) (funcall callback 42))
                   :result-function #'identity))
       (ogent-tool-registry (list spec))
       (ogent-tool-require-approval nil))
  (ogent-agent-call-async "bad-result" nil (lambda (result) (cl-incf callbacks) (princ (format "bad-result=%S\n" result))))
  (princ (format "bad-result-callbacks=%d\n" callbacks)))
