;;; history-probe.el --- Structured debug history integration -*- lexical-binding: t; -*-
(require 'ogent-agent)
(require 'ogent-debug)
(require 'ogent-ui)
(let* ((directory (ogent-test--provision-store-directory 'tools))
       (file (expand-file-name "data.txt" directory))
       (ogent-tools-project-root directory)
       (ogent-tool-registry (copy-tree ogent-tools-default-registry))
       (ogent-debug-tool-history nil)
       (ogent-tool-require-approval nil))
  (with-temp-file file (insert "abcdef\n"))
  (princ (format "read-result=%S\n" (ogent-agent-call "read" (list :file_path file :column 3))))
  (let ((entry (ogent-debug-last-tool)))
    (princ (format "history-entry=%S\n" entry))
    (princ (format "replay=%S\n" (ogent-debug-replay-tool entry))))
  (princ (format "failed-shell=%S\n" (ogent-agent-call "shell" '(:command "exit 7"))))
  (princ (format "failed-shell-history=%S\n" (ogent-debug-last-tool))))
