;;; search-config-probe.el --- Search and bound semantics -*- lexical-binding: t; -*-
(require 'ogent-agent)
(require 'ogent-tool-process)
(let* ((directory (ogent-test--provision-store-directory 'tools))
       (ogent-tools-project-root directory)
       (ogent-tool-registry (copy-tree ogent-tools-default-registry))
       (text-file (expand-file-name "data.txt" directory))
       (binary-file (expand-file-name "binary.txt" directory)))
  (with-temp-file text-file (insert "needle\nneedle\nneedle\n"))
  (let ((ogent-tools-max-file-lines 2))
    (princ (format "configured-read-default=%S\n" (ogent-agent-call "read" (list :file_path text-file))))
    (princ (format "configured-read-explicit=%S\n" (ogent-agent-call "read" (list :file_path text-file :limit 2)))))
  (with-temp-file binary-file (insert "needle\n\0needle\nneedle\n"))
  (let ((find-executable (symbol-function 'executable-find)))
    (dolist (engine '(gnu ripgrep))
      (cl-letf (((symbol-function 'executable-find)
                 (lambda (name &optional remote)
                   (if (equal name "rg")
                       (when (eq engine 'ripgrep) "/tmp/ogent-review-bin/rg")
                     (funcall find-executable name remote)))))
        (dolist (args (list (list "needle" binary-file)
                           (list "needle" text-file "*.el")))
          (condition-case err
              (princ (format "%s args=%S result=%S\n" engine args (apply #'ogent-tool-process-grep args)))
            (error (princ (format "%s args=%S error=%S\n" engine args err)))))))))
