;;; probe_encoding.el --- Distinguish tool JSON from logger coding -*- lexical-binding: t; -*-
(require 'ogent-tools)
(require 'ogent-agent)
(require 'json)
(let* ((root (ogent-test--provision-store-directory 'tools))
       (file (expand-file-name "invalid-text.txt" root))
       (ogent-tools-project-root root)
       (ogent-tool-registry (copy-tree ogent-tools-default-registry)))
  (let ((coding-system-for-write 'no-conversion))
    (with-temp-file file
      (set-buffer-multibyte nil)
      (insert (unibyte-string 255 254) "needle invalid text\n")))
  (let* ((native (ogent-agent-call "search" (list :pattern "needle" :path file)))
         (text (plist-get (aref (plist-get (plist-get native :data) :matches) 0) :text))
         (json (ogent-agent-call "search" (list :pattern "needle" :path file) 'json))
         (coding-system-for-write 'utf-8-unix))
    (write-region json nil "/work/agent_ergonomics_audit/audit/evidence/pass_3/scorerB/encoding.actual-tool.stdout.json" nil 'silent)
    (princ (concat (json-serialize
                    (list :native_text_multibyte (if (multibyte-string-p text) t :json-false)
                          :native_text_first_codepoints (vconcat (cl-subseq (string-to-list text) 0 (min 6 (length text))))
                          :json_result_multibyte (if (multibyte-string-p json) t :json-false)
                          :json_utf8_hex (mapconcat (lambda (byte) (format "%02x" byte))
                                                   (string-to-list (encode-coding-string json 'utf-8-unix)) ""))
                    :null-object :json-null :false-object :json-false) "\n")))
  (delete-directory root t))
