;;; scorerA_post_review_probe.el --- Review boundary probe -*- lexical-binding: t; -*-
(setq load-prefer-newer t)
(require 'package)
(setq package-user-dir "/tmp/ogent-fixdeps/30.2/elpa")
(package-initialize)
(require 'gptel)
(require 'jka-compr)
(setq load-suffixes (remove ".elc" load-suffixes))
(require 'json)
(require 'ogent-tools)
(require 'ogent-models)
(require 'ogent-ui-toolcalls)
(let* ((root (make-temp-file "/work/agent_ergonomics_audit/audit/partial/scorerA-post-review-" t))
       (temporary-file-directory (file-name-as-directory root))
       (default-directory (file-name-as-directory root))
       (file (expand-file-name "data.txt" root))
       (ogent-tools-project-root default-directory)
       (ogent-tool-registry nil)
       (ogent-ui-edit-preview-style 'diff-block)
       (ogent-ui--pending-diffs (make-hash-table :test #'equal))
       (ogent-ledger-enabled nil)
       rows)
  (unwind-protect
      (progn
        (ogent-tools-install-defaults)
        (with-temp-file file (insert "same same"))
        (with-temp-buffer
          (org-mode)
          (cl-letf (((symbol-function 'ogent-tool-approval-check) (lambda (&rest _) 'approved)))
            (let ((result (funcall (ogent-tool-execution-wrapper (ogent-tool-spec-get 'edit-file))
                                   file "same" "changed" nil)))
              (push (list :probe "wrapper-ambiguous-review" :result result
                          :pending_count (hash-table-count ogent-ui--pending-diffs)) rows)))
          (when (> (hash-table-count ogent-ui--pending-diffs) 0)
            (let ((id (car (hash-table-keys ogent-ui--pending-diffs))))
              (cl-letf (((symbol-function 'ogent-ui--diff-at-point) (lambda () id))
                        ((symbol-function 'ogent-ui--update-diff-status) #'ignore))
                (ogent-diff-accept))
              (push (list :probe "review-accept-ambiguous" :result (gethash id ogent-ui--pending-diffs)
                          :contents (with-temp-buffer (insert-file-contents file) (buffer-string))) rows))))
        (dolist (row (nreverse rows)) (princ (json-encode row)) (princ "\n")))
    (delete-directory root t)))
