;;; scorerA_probe.el --- Independent baseline probes -*- lexical-binding: t; -*-
(setq load-prefer-newer t)
(require 'package)
(setq package-user-dir "/tmp/ogent-fixdeps/30.2/elpa")
(package-initialize)
(require 'cl-lib)
(require 'json)
(require 'subr-x)
(require 'ogent-tools)
(require 'gptel)
(require 'ogent-models)
(require 'ogent-doctor)
(setq ogent-tools-show-progress nil)
(defun scorerA-probe (id fn)
  (let ((row (condition-case err
                 (list :probe id :result (prin1-to-string (funcall fn)))
               (error (list :probe id :error (error-message-string err)
                            :error_type (symbol-name (car err)))))))
    (princ (json-encode row))
    (princ "\n")))
(defun scorerA-async (fn args)
  (let (events finished)
    (let ((proc (apply fn (append args (list (lambda (type data)
                                             (push (list type data) events)
                                             (when (memq type '(done error))
                                               (setq finished t)))))))
          (deadline (+ (float-time) 4)))
      (while (and (not finished) (< (float-time) deadline))
        (accept-process-output nil 0.05))
      (unless finished (when (processp proc) (delete-process proc)))
      (nreverse events))))
(let* ((fixture (make-temp-file "/work/agent_ergonomics_audit/audit/partial/scorerA-fixture-" t))
       (default-directory (file-name-as-directory fixture))
       (ogent-tools-project-root default-directory))
  (unwind-protect
      (progn
        (with-temp-file (expand-file-name "alpha.txt" fixture)
          (insert "alpha needle\nbeta\nneedle again\n"))
        (make-directory (expand-file-name "nested/deep" fixture) t)
        (with-temp-file (expand-file-name "nested/deep/deep.txt" fixture)
          (insert "deep needle\n"))
        (with-temp-file (expand-file-name "nested/near.txt" fixture)
          (insert "near needle\n"))
        (scorerA-probe "read-valid-1" (lambda () (ogent-tool--read-file "alpha.txt" 1 2)))
        (scorerA-probe "read-valid-2" (lambda () (ogent-tool--read-file "alpha.txt" 1 2)))
        (scorerA-probe "read-negative-offset" (lambda () (ogent-tool--read-file "alpha.txt" -1 2)))
        (scorerA-probe "read-negative-limit" (lambda () (ogent-tool--read-file "alpha.txt" 1 -2)))
        (scorerA-probe "read-missing" (lambda () (ogent-tool--read-file "missing.txt")))
        (scorerA-probe "glob-valid-1" (lambda () (ogent-tool--glob "*.txt")))
        (scorerA-probe "glob-valid-2" (lambda () (ogent-tool--glob "*.txt")))
        (scorerA-probe "glob-recursive" (lambda () (ogent-tool--glob "**/*.txt")))
        (scorerA-probe "glob-missing-root" (lambda () (ogent-tool--glob "*.txt" "missing-root")))
        (scorerA-probe "grep-valid-1" (lambda () (ogent-tool--grep "needle" "alpha.txt")))
        (scorerA-probe "grep-valid-2" (lambda () (ogent-tool--grep "needle" "alpha.txt")))
        (scorerA-probe "grep-invalid-regex" (lambda () (ogent-tool--grep "[" "alpha.txt")))
        (scorerA-probe "grep-leading-hyphen" (lambda () (ogent-tool--grep "-needle" "alpha.txt")))
        (scorerA-probe "grep-negative-context" (lambda () (ogent-tool--grep "needle" "alpha.txt" nil -1)))
        (scorerA-probe "grep-quoted-glob" (lambda () (ogent-tool--grep "needle" fixture "*.txt'; printf SCORERA_INJECTION; #")))
        (scorerA-probe "grep-async-valid-1" (lambda () (scorerA-async #'ogent-tool--grep-async '("needle" "alpha.txt" nil 0))))
        (scorerA-probe "grep-async-valid-2" (lambda () (scorerA-async #'ogent-tool--grep-async '("needle" "alpha.txt" nil 0))))
        (scorerA-probe "grep-async-invalid-regex" (lambda () (scorerA-async #'ogent-tool--grep-async '("[" "alpha.txt" nil 0))))
        (scorerA-probe "bash-valid-1" (lambda () (ogent-tool--bash "printf hello; printf diagnostic >&2; exit 7" nil 2)))
        (scorerA-probe "bash-valid-2" (lambda () (ogent-tool--bash "printf hello; printf diagnostic >&2; exit 7" nil 2)))
        (scorerA-probe "bash-empty" (lambda () (ogent-tool--bash "" nil 2)))
        (scorerA-probe "bash-invalid-timeout" (lambda () (ogent-tool--bash "printf hello" nil "2")))
        (scorerA-probe "bash-async-valid-1" (lambda () (scorerA-async #'ogent-tool--bash-async '("printf hello; printf diagnostic >&2; exit 7" nil 2))))
        (scorerA-probe "bash-async-valid-2" (lambda () (scorerA-async #'ogent-tool--bash-async '("printf hello; printf diagnostic >&2; exit 7" nil 2))))
        (scorerA-probe "write-valid" (lambda () (ogent-tool--write-file "write.txt" "one\n")))
        (scorerA-probe "write-repeat" (lambda () (ogent-tool--write-file "write.txt" "one\n")))
        (scorerA-probe "write-invalid-content" (lambda () (ogent-tool--write-file "write.txt" 42)))
        (scorerA-probe "write-invalid-content-after" (lambda () (ogent-tool--read-file "write.txt")))
        (with-temp-file (expand-file-name "edit.txt" fixture) (insert "same same"))
        (scorerA-probe "edit-ambiguous" (lambda () (ogent-tool--edit-file "edit.txt" "same" "changed")))
        (scorerA-probe "edit-ambiguous-file" (lambda () (ogent-tool--read-file "edit.txt")))
        (scorerA-probe "edit-missing-old" (lambda () (ogent-tool--edit-file "edit.txt" "absent" "changed")))
        (setq ogent-tool-registry nil ogent--tools-registered nil ogent--tool-specs-registered nil)
        (ogent-tools-install-defaults)
        (scorerA-probe "tool-get-valid" (lambda () (gptel-tool-name (ogent-tool-get 'read-file))))
        (scorerA-probe "tool-get-string" (lambda () (ogent-tool-get "read-file")))
        (scorerA-probe "tool-get-typo" (lambda () (ogent-tool-get 'read-fiel)))
        (scorerA-probe "tool-spec-valid" (lambda () (ogent-tool-spec-get 'read-file)))
        (scorerA-probe "tool-spec-string" (lambda () (ogent-tool-spec-get "read-file")))
        (scorerA-probe "available-tools-1" (lambda () (let ((ogent-tools-enabled t)) (mapcar #'gptel-tool-name (ogent-tools-enabled-list)))))
        (scorerA-probe "available-tools-2" (lambda () (let ((ogent-tools-enabled t)) (mapcar #'gptel-tool-name (ogent-tools-enabled-list)))))
        (scorerA-probe "available-tools-unknown-filter" (lambda () (let ((ogent-tools-enabled '(read-fiel))) (ogent-tools-enabled-list))))
        (scorerA-probe "wrapper-stale" (lambda () (let ((fn (ogent-tool-execution-wrapper (ogent-tool-spec-get 'read-file)))) (setq ogent-tool-registry nil) (funcall fn "alpha.txt"))))
        (ogent-tools-install-defaults)
        (scorerA-probe "wrapper-arity-invalid" (lambda () (let ((fn (ogent-tool-execution-wrapper (ogent-tool-spec-get 'read-file)))) (cl-letf (((symbol-function 'ogent-tool-approval-check) (lambda (&rest _) 'approved))) (funcall fn "alpha.txt" 1 1 "extra")))))
        (let ((ogent-doctor-checks '((:id fixture :label "Fixture" :category environment :fn (lambda () '(ok . "healthy")) :remediation "No action"))))
          (scorerA-probe "doctor-run-1" #'ogent-doctor-run)
          (scorerA-probe "doctor-run-2" #'ogent-doctor-run)
          (scorerA-probe "doctor-batch" (lambda ()
                                          (with-temp-buffer
                                            (let* ((standard-output (current-buffer))
                                                   (code (ogent-doctor-batch)))
                                              (list :exit-code code :stdout (buffer-string)))))))
        (let ((ogent-doctor-checks '((:id broken :label "Broken fixture" :category environment :fn (lambda () (error "Fixture crash")) :remediation "Correct fixture"))))
          (scorerA-probe "doctor-crash-contained" #'ogent-doctor-run))
        (dolist (fn '(ogent-tool--read-file ogent-tool--glob ogent-tool--grep ogent-tool--grep-async ogent-tool--bash ogent-tool--bash-async ogent-tool--write-file ogent-tool--edit-file ogent-tool-get ogent-tool-spec-get ogent-tools-enabled-list ogent-tool-execution-wrapper ogent-doctor-run ogent-doctor-batch))
          (scorerA-probe (concat "doc-" (symbol-name fn)) (lambda () (documentation fn)))))
    (ogent-tools-cancel-all)
    (delete-directory fixture t)))
