;;; scorerB-probe.el --- Independent baseline probes -*- lexical-binding: t; -*-
(setq load-prefer-newer t)
(require 'cl-lib)
(require 'subr-x)
(require 'json)
(require 'jka-compr)
(setq load-suffixes '(".el" ".el.gz"))
(dolist (dir (directory-files "/tmp/ogent-fixdeps/30.2/elpa" t "^[^.].*"))
  (when (file-directory-p dir) (push dir load-path)))
(require 'gptel)
(require 'ogent-tools)
(require 'ogent-models)
(require 'ogent-doctor)
(setq ogent-tools-show-progress nil ogent-tools-grep-timeout 2)
(setq user-emacs-directory "/work/agent_ergonomics_audit/audit/partial/scorerB_post_fixture/emacs/")
(defvar scorerB-dir "/work/agent_ergonomics_audit/audit/partial/scorerB_post_fixture/")
(make-directory scorerB-dir t)
(setq ogent-tools-project-root scorerB-dir default-directory scorerB-dir)
(defun scorerB-emit (label value)
  (princ (json-encode `((label . ,label) (value . ,(prin1-to-string value)))))
  (princ "\n"))
(defun scorerB-probe (label thunk)
  (condition-case err (scorerB-emit label (funcall thunk))
    (error (scorerB-emit label (list :error (car err) :message (error-message-string err))))))
(ogent-tool--write-file "alpha.el" "one\nrepeat\nrepeat\n")
(ogent-tool--write-file "nested/deeper/deep.el" "deep match\n")
(dolist (name '(ogent-tool--read-file ogent-tool--glob ogent-tool--grep ogent-tool--grep-async
                ogent-tool--bash ogent-tool--bash-async ogent-tool--write-file ogent-tool--edit-file
                ogent-tool-get ogent-tool-spec-get ogent-tools-enabled-list ogent-tool-execution-wrapper
                ogent-doctor-run ogent-doctor-batch))
  (scorerB-emit (format "doc:%s" name) (list :args (help-function-arglist name) :doc (documentation name))))
(scorerB-probe "read:normal-repeat" (lambda () (list (ogent-tool--read-file "alpha.el") (ogent-tool--read-file "alpha.el"))))
(scorerB-probe "read:missing" (lambda () (ogent-tool--read-file "absent.el")))
(scorerB-probe "read:negative-offset" (lambda () (ogent-tool--read-file "alpha.el" -2 2)))
(scorerB-probe "read:negative-limit" (lambda () (ogent-tool--read-file "alpha.el" 1 -1)))
(scorerB-probe "glob:normal-repeat" (lambda () (list (ogent-tool--glob "*.el") (ogent-tool--glob "*.el"))))
(scorerB-probe "glob:recursive" (lambda () (ogent-tool--glob "**/*.el")))
(scorerB-probe "grep:normal-repeat" (lambda () (list (ogent-tool--grep "repeat" "alpha.el") (ogent-tool--grep "repeat" "alpha.el"))))
(scorerB-probe "grep:no-matches" (lambda () (ogent-tool--grep "absent" "alpha.el")))
(scorerB-probe "grep:bad-regex" (lambda () (ogent-tool--grep "[" "alpha.el")))
(scorerB-probe "grep:empty-pattern" (lambda () (ogent-tool--grep "" "alpha.el")))
(scorerB-probe "grep:negative-context" (lambda () (ogent-tool--grep "repeat" "alpha.el" nil -1)))
(scorerB-probe "grep:glob-quote" (lambda () (ogent-tool--grep "repeat" "." "*.el'")))
(scorerB-probe "grep:glob-injection" (lambda () (list (ogent-tool--grep "repeat" "." "*.el'; printf INJECTED > injection-marker; #") (file-exists-p "injection-marker"))))
(defun scorerB-await (proc)
  (let ((deadline (+ (float-time) 3)))
    (while (and (processp proc) (process-live-p proc) (< (float-time) deadline))
      (accept-process-output nil .05))
    (accept-process-output nil .05)
    (when (and (processp proc) (process-live-p proc)) (kill-process proc))))
(scorerB-probe "grep-async:normal" (lambda () (let (events) (scorerB-await (ogent-tool--grep-async "repeat" "alpha.el" nil 0 (lambda (kind data) (push (list kind data) events)))) (nreverse events))))
(scorerB-probe "grep-async:bad-regex" (lambda () (let (events) (scorerB-await (ogent-tool--grep-async "[" "alpha.el" nil 0 (lambda (kind data) (push (list kind data) events)))) (nreverse events))))
(scorerB-probe "bash:normal-repeat" (lambda () (list (ogent-tool--bash "printf hello; printf warning >&2; exit 3" nil 2) (ogent-tool--bash "printf hello; printf warning >&2; exit 3" nil 2))))
(scorerB-probe "bash:timeout" (lambda () (ogent-tool--bash "sleep 1" nil .05)))
(scorerB-probe "bash:wrong-timeout" (lambda () (ogent-tool--bash "printf harmless" nil "2")))
(scorerB-probe "bash-async:normal" (lambda () (let (events) (scorerB-await (ogent-tool--bash-async "printf hello; printf warning >&2; exit 3" nil 2 (lambda (kind data) (push (list kind data) events)))) (nreverse events))))
(scorerB-probe "bash-async:timeout" (lambda () (let (events) (scorerB-await (ogent-tool--bash-async "sleep 1" nil .05 (lambda (kind data) (push (list kind data) events)))) (nreverse events))))
(scorerB-probe "write:normal-repeat" (lambda () (list (ogent-tool--write-file "write.el" "first") (ogent-tool--write-file "write.el" "second") (ogent-tool--read-file "write.el"))))
(scorerB-probe "write:invalid-content" (lambda () (ogent-tool--write-file "write.el" 10)))
(scorerB-probe "edit:duplicate" (lambda () (list (ogent-tool--edit-file "alpha.el" "repeat" "changed") (ogent-tool--read-file "alpha.el"))))
(scorerB-probe "edit:missing" (lambda () (ogent-tool--edit-file "alpha.el" "absent" "new")))
(ogent-tools-install-defaults)
(scorerB-probe "registry:get" (lambda () (let ((obj (ogent-tool-get 'read-file))) (list :name (gptel-tool-name obj) :args (gptel-tool-args obj) :async (gptel-tool-async obj)))))
(scorerB-probe "registry:unknown" (lambda () (ogent-tool-get 'read-fiel)))
(scorerB-probe "registry:string-name" (lambda () (ogent-tool-get "read-file")))
(scorerB-probe "registry:spec" (lambda () (ogent-tool-spec-get 'read-file)))
(scorerB-probe "registry:enabled-repeat" (lambda () (let ((ogent-tools-enabled t)) (list (mapcar #'gptel-tool-name (ogent-tools-enabled-list)) (mapcar #'gptel-tool-name (ogent-tools-enabled-list))))))
(scorerB-probe "registry:typo-enabled" (lambda () (let ((ogent-tools-enabled '(read-fiel))) (ogent-tools-enabled-list))))
(scorerB-probe "wrapper:normal" (lambda () (funcall (ogent-tool-execution-wrapper (ogent-tool-spec-get 'read-file)) "alpha.el")))
(scorerB-probe "wrapper:unknown" (lambda () (funcall (ogent-tool-execution-wrapper '(:name read-fiel :args nil :function ignore)))))
(scorerB-probe "wrapper:denied" (lambda () (let ((ogent-tool-require-approval t) (ogent-tool--denied-tools '("bash"))) (funcall (ogent-tool-execution-wrapper (ogent-tool-spec-get 'bash)) "printf harmless"))))
(scorerB-probe "wrapper:wrong-arity" (lambda () (funcall (ogent-tool-execution-wrapper (ogent-tool-spec-get 'read-file)))))
(scorerB-probe "doctor:normal" (lambda () (ogent-doctor-run)))
(scorerB-probe "doctor:normal-repeat-equal" (lambda () (equal (ogent-doctor-run) (ogent-doctor-run))))
(scorerB-probe "doctor:batch" (lambda () (ogent-doctor-batch)))


(require 'ogent-agent)
(scorerB-probe "read:page-guidance" (lambda () (ogent-tool--read-file "alpha.el" 1 1)))
(scorerB-probe "read:past-end" (lambda () (ogent-tool--read-file "alpha.el" 999 1)))
(scorerB-probe "grep:leading-dash" (lambda () (ogent-tool--write-file "dash.el" "-needle\n") (ogent-tool--grep "-needle" "dash.el")))
(scorerB-probe "edit:empty" (lambda () (ogent-tool--edit-file "alpha.el" "" "new" t)))
(scorerB-probe "write:content-preserved" (lambda () (ogent-tool--read-file "write.el")))
(scorerB-probe "registry:string-and-alias" (lambda () (list (gptel-tool-name (ogent-tool-get "read-file")) (gptel-tool-name (ogent-tool-get "read_file")))))
(scorerB-probe "registry:ensure-typo" (lambda () (ogent-tool-ensure "read-fiel")))
(scorerB-probe "registry:spec-alias" (lambda () (ogent-tool-spec-get "read_file")))
(scorerB-probe "wrapper:excess-arguments" (lambda () (funcall (ogent-tool-execution-wrapper (ogent-tool-spec-get 'read-file)) "alpha.el" 1 1 "extra")))
(scorerB-probe "wrapper:duplicate-edit-review" (lambda () (with-temp-buffer (org-mode) (let ((ogent-tool-require-approval nil) (ogent-ui-edit-preview-style 'diff-block) (ogent-ui--pending-diffs (make-hash-table :test 'equal))) (funcall (ogent-tool-execution-wrapper (ogent-tool-spec-get 'edit-file)) "alpha.el" "repeat" "changed" nil)))))
(scorerB-probe "capabilities:repeat" (lambda () (let ((a (ogent-agent-capabilities 'json)) (b (ogent-agent-capabilities 'json))) (list :byte-identical (equal a b) :result a))))
(scorerB-probe "guide:current" (lambda () (ogent-agent-guide)))
(scorerB-probe "triage:current" (lambda () (ogent-agent-triage 'json)))
(scorerB-probe "doctor:json" (lambda () (let (code) (list :stdout (with-output-to-string (setq code (ogent-doctor-batch nil 'json))) :code code))))
(scorerB-probe "doctor:json-repeat" (lambda () (equal (with-output-to-string (ogent-doctor-batch nil 'json)) (with-output-to-string (ogent-doctor-batch nil 'json)))))
(scorerB-probe "doctor:format-error" (lambda () (ogent-doctor-batch nil 'jsno)))
(ogent-tools-cancel-all)
