;;; tasks.el --- Source-blind canonical exercise -*- lexical-binding: t; -*-
(require 'json)
(require 'cl-lib)
(defconst audit-root "/work/agent_ergonomics_audit/audit/agent_simulations/post_pass_3/final_freeze/")
(defconst audit-fixtures "/work/agent_ergonomics_audit/audit/agent_simulations/post_pass_3/fixtures/")
(defvar audit-roundtrips 0)
(defvar audit-task-summaries nil)
(defun audit-form (form &optional roundtrip)
  (when roundtrip (cl-incf audit-roundtrips))
  (princ (format "FORM %S\n" form))
  (let ((result (eval form t)))
    (princ (format "RESULT %S\n" result))
    result))
(defun audit-task (id name fn)
  (let ((before audit-roundtrips) verdict)
    (princ (format "TASK_START %d %s\n" id name))
    (setq verdict (condition-case err (funcall fn)
                    (error (list :success :json-false :failure_diagnosis (format "%S" err)))))
    (let ((summary (append (list :task id :name name :replay_attempts 1
                                 :regression_roundtrips (- audit-roundtrips before))
                           verdict)))
      (push summary audit-task-summaries)
      (princ (concat "TASK_SUMMARY " (json-serialize summary :null-object :json-null :false-object :json-false) "\n")))))
(defun audit-walk (name args)
  "Collect successful pages and honest terminal, with a bounded loop."
  (let ((page (audit-form `(ogent-agent-call ,name ',args) t)) pages (calls 0))
    (while (and (equal (plist-get page :status) "ok") (< calls 1000))
      (push page pages)
      (cl-incf calls)
      (setq page (audit-form `(ogent-agent-next ',page) t)))
    (list :pages (nreverse pages) :terminal page)))
(audit-form '(require 'ogent))
(audit-form '(setq ogent-tools-project-root "/work/"))
(audit-form '(list :rg (executable-find "rg") :grep (executable-find "grep")))
(audit-task
 1 "Discover named execution, search shape, and async support"
 (lambda ()
   (let* ((info (audit-form '(ogent-agent-describe "search") t))
          (tool (plist-get info :tool))
          (args (plist-get tool :call_arguments))
          (names (mapcar (lambda (x) (plist-get x :name)) args))
          (ok (and (equal (plist-get tool :execution) "ogent-agent-call")
                   (member "pattern" names) (member "path" names)
                   (member "offset" names) (member "limit" names)
                   (eq (plist-get tool :async_sdk) t))))
     (list :success (if ok t :json-false) :call_arguments (vconcat names)
           :async_sdk (plist-get tool :async_sdk)
           :failure_diagnosis (if ok :json-null "Discovery did not expose expected named shape/support")))))
(audit-task
 2 "Page README seven lines at a time and preserve positions"
 (lambda ()
   (let* ((walk (audit-walk "read" '(:file_path "README.org" :limit 7)))
          (pages (plist-get walk :pages))
          (terminal (plist-get walk :terminal))
          (lines (apply #'append (mapcar (lambda (p) (append (plist-get (plist-get p :data) :lines) nil)) pages)))
          (expected (with-temp-buffer (insert-file-contents "/work/README.org") (buffer-string)))
          (joined (mapconcat (lambda (line) (plist-get line :text)) lines "\n"))
          (newline (eq (plist-get (plist-get (car pages) :data) :ends_with_newline) t))
          (numbers (mapcar (lambda (line) (plist-get line :number)) lines))
          (ok (and (equal (plist-get terminal :status) "done")
                   (equal numbers (number-sequence 1 (length lines)))
                   (cl-every (lambda (x) (= (plist-get x :column) 1)) lines)
                   (equal expected (concat joined (if newline "\n" ""))))))
     (list :success (if ok t :json-false) :pages (length pages) :line_count (length lines)
           :terminal_status (plist-get terminal :status) :preserved_content (if ok t :json-false)
           :failure_diagnosis (if ok :json-null "Terminal or reconstruction/line positions disagreed")))))
(audit-task
 3 "Discover all 105 .el files without duplicates"
 (lambda ()
   (let* ((walk (audit-walk "files" `(:pattern "**/*.el" :path ,(concat audit-fixtures "glob") :limit 40)))
          (pages (plist-get walk :pages))
          (objects (apply #'append (mapcar (lambda (p) (append (plist-get (plist-get p :data) :files) nil)) pages)))
          (paths (mapcar (lambda (x) (plist-get x :path)) objects))
          (ok (and (= (length paths) 105) (= (length (delete-dups (copy-sequence paths))) 105)
                   (equal (plist-get (plist-get walk :terminal) :status) "done"))))
     (list :success (if ok t :json-false) :pages (length pages) :count (length paths)
           :unique_count (length (delete-dups (copy-sequence paths)))
           :paths (vconcat paths) :terminal (plist-get walk :terminal)
           :failure_diagnosis (if ok :json-null "File count, uniqueness, or terminal disagreed")))))
(audit-task
 4 "Page 250 exact match locations with colon/newline filename"
 (lambda ()
   (let* ((target (concat audit-fixtures "search/strange:segment\nline.el"))
          (walk (audit-walk "search" `(:pattern "needle" :path ,(concat audit-fixtures "search") :limit 100)))
          (pages (plist-get walk :pages))
          (matches (apply #'append (mapcar (lambda (p) (append (plist-get (plist-get p :data) :matches) nil)) pages)))
          (locations (mapcar (lambda (m) (list (plist-get m :path) (plist-get m :line))) matches))
          (ok (and (= (length matches) 250)
                   (equal (mapcar #'cadr locations) (number-sequence 1 250))
                   (cl-every (lambda (m) (and (equal (plist-get m :path) target)
                                              (equal (plist-get m :text) (format "needle fixture line %03d" (plist-get m :line))))) matches)
                   (equal (plist-get (plist-get walk :terminal) :status) "done"))))
     (list :success (if ok t :json-false) :pages (length pages) :count (length matches)
           :unique_count (length (delete-dups (copy-sequence locations))) :terminal (plist-get walk :terminal)
           :failure_diagnosis (if ok :json-null "Search count, filename, line/text identity, or terminal disagreed")))))
(audit-task
 5 "Distinguish no matches from invalid regex, including empty directory"
 (lambda ()
   (let ((outcomes nil) (ok t))
     (dolist (directory '("nonempty" "empty"))
       (dolist (pattern '("unmatched-needle" "["))
         (let* ((result (audit-form `(ogent-agent-call "search" '(:pattern ,pattern :path ,(concat audit-fixtures directory))) t))
                (invalid (equal pattern "["))
                (valid (if invalid
                           (and (equal (plist-get result :status) "error")
                                (equal (plist-get (plist-get result :error) :code) "search_failed"))
                         (and (equal (plist-get result :status) "ok")
                              (= (length (plist-get (plist-get result :data) :matches)) 0)))))
           (unless valid (setq ok nil))
           (push (list :directory directory :pattern pattern :result result) outcomes))))
     (list :success (if ok t :json-false) :outcomes (vconcat (nreverse outcomes))
           :failure_diagnosis (if ok :json-null "Empty search versus invalid regex distinction failed")))))
(audit-task
 6 "Approval calls never prompt/mutate; unsafe batch preflight rejects"
 (lambda ()
   (let* ((shell-file (concat audit-fixtures "shell-must-not-exist"))
          (write-file (concat audit-fixtures "write-must-not-exist"))
          (prompts 0) (reads 0) shell write batch)
     ;; These guards detect prompts rather than granting or changing policy.
     (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) (cl-incf prompts) (error "Forbidden prompt")))
               ((symbol-function 'y-or-n-p) (lambda (&rest _) (cl-incf prompts) (error "Forbidden prompt"))))
       (setq shell (audit-form `(ogent-agent-call "shell" '(:command ,(concat "touch " shell-file))) t)
             write (audit-form `(ogent-agent-call "write" '(:file_path ,write-file :content "must not mutate")) t)))
     (let ((original (symbol-function 'insert-file-contents)))
       (cl-letf (((symbol-function 'insert-file-contents)
                  (lambda (file &rest rest)
                    (when (equal (expand-file-name file) "/work/README.org") (cl-incf reads))
                    (apply original file rest))))
         (setq batch (audit-form `(ogent-agent-batch
                                   '[(:tool "read" :args (:file_path "README.org" :limit 1))
                                     (:tool "shell" :args (:command ,(concat "touch " shell-file)))]) t))))
     (let ((ok (and (equal (plist-get shell :status) "approval_required")
                    (equal (plist-get write :status) "approval_required")
                    (equal (plist-get (plist-get batch :error) :code) "unsafe_batch")
                    (= prompts 0) (= reads 0)
                    (not (file-exists-p shell-file)) (not (file-exists-p write-file)))))
       (list :success (if ok t :json-false) :shell shell :write write :batch batch
             :prompt_count prompts :read_count_before_rejection reads
             :shell_mutated (if (file-exists-p shell-file) t :json-false)
             :write_mutated (if (file-exists-p write-file) t :json-false)
             :failure_diagnosis (if ok :json-null "Approval/preflight status, prompt, read, or mutation disagreed"))))))
(audit-task
 7 "Compose glob/search/read in one batch"
 (lambda ()
   (let* ((result (audit-form `(ogent-agent-batch
                              '[(:tool "files" :args (:pattern "**/*.el" :path ,(concat audit-fixtures "glob") :limit 5))
                                (:tool "search" :args (:pattern "needle" :path ,(concat audit-fixtures "search") :limit 5))
                                (:tool "read" :args (:file_path "README.org" :limit 7))]) t))
          (data (plist-get result :data))
          (results (plist-get data :results))
          (ok (and (equal (plist-get result :status) "ok")
                   (= (plist-get data :requested) 3) (= (plist-get data :completed) 3)
                   (= (length results) 3)
                   (cl-every (lambda (x) (equal (plist-get x :status) "ok")) results))))
     (list :success (if ok t :json-false) :requested (plist-get data :requested) :completed (plist-get data :completed)
           :failure_diagnosis (if ok :json-null "Batch result did not contain three successful calls")))))
(audit-task
 8 "Async search finishes once and supports cancellation"
 (lambda ()
   (let ((normal-count 0) (cancel-count 0) normal-result cancel-result normal-process cancel-process)
     (setq normal-process
           (audit-form `(ogent-agent-call-async
                         "search" '(:pattern "needle" :path ,(concat audit-fixtures "search") :limit 5)
                         ,(lambda (result) (cl-incf normal-count) (setq normal-result result)
                            (princ (format "CALLBACK normal %S\n" result)))) t))
     (let ((deadline (+ (float-time) 10)))
       (while (and (= normal-count 0) (< (float-time) deadline)) (accept-process-output nil 0.05)))
     (accept-process-output nil 0.1)
     ;; Inspect cancellation help again after the documented async call has lazy-loaded support.
     (audit-form '(documentation 'ogent-tool-process-cancel) t)
     (setq cancel-process
           (audit-form `(ogent-agent-call-async
                         "search" '(:pattern "needle" :path ,(concat audit-fixtures "search") :limit 5)
                         ,(lambda (result) (cl-incf cancel-count) (setq cancel-result result)
                            (princ (format "CALLBACK cancelled %S\n" result)))) t))
     (when (processp cancel-process)
       (audit-form `(ogent-tool-process-cancel ,cancel-process) t))
     (let ((deadline (+ (float-time) 10)))
       (while (and (= cancel-count 0) (< (float-time) deadline)) (accept-process-output nil 0.05)))
     (accept-process-output nil 0.1)
     (let ((ok (and (= normal-count 1) (= cancel-count 1)
                    (equal (plist-get normal-result :status) "ok")
                    (processp normal-process) (processp cancel-process)
                    (equal (plist-get (plist-get cancel-result :error) :code) "cancelled"))))
       (list :success (if ok t :json-false) :normal_callback_count normal-count :cancel_callback_count cancel-count
             :normal_returned_process (if (processp normal-process) t :json-false)
             :cancel_returned_process (if (processp cancel-process) t :json-false)
             :normal_result normal-result :cancel_result cancel-result
             :failure_diagnosis (if ok :json-null "Async terminal cardinality, returned process, or cancellation disagreed"))))))
(with-temp-file (concat audit-root "task-results.json")
  (insert (json-serialize (vconcat (nreverse audit-task-summaries)) :null-object :json-null :false-object :json-false) "\n"))
