;;; independent-probe.el --- Round five independent probes -*- lexical-binding: t; -*-
(require 'ogent-agent)
(require 'ogent-tool-process)
(require 'cl-lib)

(defun review5-print (label value)
  (let ((print-length nil) (print-level nil))
    (princ (format "%s %S\n" label value))))

(defun review5-write (root name contents)
  (let ((file (expand-file-name name root)))
    (make-directory (file-name-directory file) t)
    (let ((coding-system-for-write 'utf-8-unix))
      (with-temp-file file (insert contents)))
    file))

;; Compare whole ordered match identities and context through both real engines.
(let* ((root (ogent-test--provision-store-directory 'tools))
       (ogent-tools-project-root root)
       (ogent-tools-max-output-chars 200000)
       (finder (symbol-function 'executable-find))
       names results)
  (dotimes (index 270)
    (push (format "a%03d.txt" index) names))
  (setq names (append names '("a000/deep.txt" "a128/deep.txt" "é.txt"
                              "a[x].txt" "a?b.txt" "a\\b.txt" "a{b,c}.txt"
                              "a!b.txt" "a:\nb.txt" ".hidden.txt" "end/z.txt")))
  (dolist (name names)
    (review5-write root name "before\r\nneedle1\r\nneedle2\r\nafter\r\n"))
  (review5-write root "binary.txt" "needle1\n\0needle2\n")
  (review5-write root "zexcluded.txt" "needle1\n")
  (review5-write root ".git/hidden.txt" "needle1\n")
  (dolist (engine '(gnu rg))
    (cl-letf (((symbol-function 'executable-find)
               (lambda (name &optional remote)
                 (if (equal name "rg") (and (eq engine 'rg) "/tmp/ogent-test-rg")
                   (funcall finder name remote)))))
      (let ((offset 0) matches snapshot total pages)
        (while offset
          (let ((page (ogent-tool-process-grep "needle" root "[!z]*.txt" 1 offset 173)))
            (when snapshot (cl-assert (equal snapshot (plist-get page :snapshot))))
            (setq snapshot (plist-get page :snapshot)
                  total (plist-get page :total_matches)
                  matches (append matches (append (plist-get page :matches) nil))
                  pages (cons (list offset (length (plist-get page :matches))) pages)
                  offset (and (eq (plist-get page :has_more) t) (plist-get page :next_offset)))))
        (push (list engine :total total :snapshot snapshot :matches matches) results)
        (review5-print (format "ORDERED SEARCH %s" engine)
                       (list :total total :pages (nreverse pages)
                             :paths (mapcar (lambda (match)
                                              (list (file-relative-name (plist-get match :path) root)
                                                    (plist-get match :line))) matches))))))
  (let ((gnu (cdr (assq 'gnu results))) (rg (cdr (assq 'rg results))))
    (cl-assert (= (plist-get gnu :total) 560))
    (cl-assert (equal gnu rg))
    (review5-print "ORDER, CONTEXT, BINARY AND SNAPSHOT PARITY" t)))

;; Reassemble Unicode long lines and blank lines from minimal-budget SDK pages.
(let* ((root (ogent-test--provision-store-directory 'tools))
       (file (review5-write root "read.txt" "αβγδε\n\nsecond\nlast"))
       (ogent-tools-max-output-chars 3)
       (ogent-tool-registry (copy-tree ogent-tools-default-registry))
       (page (ogent-agent-call "read" (list :file_path file :limit 2)))
       (rebuilt (make-hash-table :test #'eql)) positions)
  (while (equal (plist-get page :status) "ok")
    (dolist (line (append (plist-get (plist-get page :data) :lines) nil))
      (let* ((number (plist-get line :number))
             (prior (gethash number rebuilt "")))
        (cl-assert (= (plist-get line :column) (1+ (length prior))))
        (puthash number (concat prior (plist-get line :text)) rebuilt)
        (push (list number (plist-get line :column) (plist-get line :partial)) positions)))
    (setq page (ogent-agent-next page)))
  (cl-assert (equal (plist-get page :status) "done"))
  (cl-assert (equal (mapconcat (lambda (number) (gethash number rebuilt)) '(1 2 3 4) "\n")
                    "αβγδε\n\nsecond\nlast"))
  (review5-print "UNICODE READ REASSEMBLED" (nreverse positions)))

;; Cancel two live processes through the public global owner.
(let* ((root (ogent-test--provision-store-directory 'tools))
       (ogent-tools--active-processes nil)
       (callbacks 0) terminals failures processes)
  (dotimes (_ 2)
    (push (ogent-tool-process-bash-async
           "printf partial; sleep 10" root 30
           (lambda (data failure)
             (cl-incf callbacks) (push data terminals) (push failure failures))) processes))
  (accept-process-output nil 0.01)
  (cl-assert (= (ogent-tools-active-count) 2))
  (ogent-tools-cancel-all)
  (accept-process-output nil 0.05)
  (cl-assert (= callbacks 2))
  (cl-assert (= (ogent-tools-active-count) 0))
  (cl-assert (cl-every #'null failures))
  (cl-assert (cl-every (lambda (data) (eq (plist-get data :cancelled) t)) terminals))
  (cl-assert (cl-every (lambda (process) (not (process-live-p process))) processes))
  (review5-print "GLOBAL CANCELLATION" (list :callbacks callbacks :results terminals)))
