;;; flow-probe.el --- Independent third-round flow probes -*- lexical-binding: t; -*-
(require 'ogent-agent)
(require 'ogent-tools)
(require 'ogent-tool-process)
(require 'ogent-debug)
(require 'cl-lib)

(defun round3-output (label data)
  (princ (format "%s %S\n" label data)))

(let* ((root (ogent-test--provision-store-directory 'tools))
       (ogent-tool-registry (copy-tree ogent-tools-default-registry))
       (ogent-tools-project-root root)
       (ogent-tool-require-approval nil)
       (finder (symbol-function 'executable-find))
       (rg "/tmp/ogent-test-rg"))
  (dolist (file '("src/direct.txt" "src/deep/nested.txt" "top.txt" "literal[1]{a}!*.txt"))
    (let ((path (expand-file-name file root)))
      (make-directory (file-name-directory path) t)
      (with-temp-file path (insert "before\nneedle\nafter\n"))))
  (dolist (filter '("*.txt" "src/*.txt" "src/**/*.txt" "!*.txt"))
    (dolist (engine '(gnu rg))
      (cl-letf (((symbol-function 'executable-find)
                 (lambda (name) (if (equal name "rg") (and (eq engine 'rg) rg)
                                  (funcall finder name)))))
        (round3-output
         (format "FILTER %S %s" filter engine)
         (ogent-agent-call "search" (list :pattern "needle" :path root :glob_filter filter))))))
  (dolist (engine '(gnu rg))
    (cl-letf (((symbol-function 'executable-find)
               (lambda (name) (if (equal name "rg") (and (eq engine 'rg) rg)
                                (funcall finder name)))))
      (round3-output (format "LITERAL %s" engine)
                     (ogent-agent-call "search"
                                       (list :pattern "needle" :path (expand-file-name "literal[1]{a}!*.txt" root))))))
  (let ((ogent-tools-max-file-lines 1))
    (round3-output "READ DEFAULT" (ogent-agent-call "read" '(:file_path "top.txt"))))
  (let* ((file (concat root "/" (unibyte-string 255) ".txt"))
         (callbacks 0) terminal)
    (with-temp-file file (insert "contents\n"))
    (round3-output "RAW FILENAME SYNC" (ogent-agent-call "read" (list :file_path file) 'json))
    (ogent-agent-call-async "read" (list :file_path file)
                          (lambda (data) (cl-incf callbacks) (setq terminal data)) 'json)
    (round3-output "RAW FILENAME ASYNC" (list :callbacks callbacks :result terminal)))
  (let ((ogent-debug-tool-history nil))
    (ogent-agent-call "read" '(:file_path "top.txt" :column 3 :limit 1))
    (round3-output "HISTORY READ" (ogent-debug-last-tool))
    (ogent-debug-replay-tool (ogent-debug-last-tool))
    (round3-output "HISTORY REPLAYED" (ogent-debug-last-tool))
    (ogent-agent-call "shell" '(:command "printf retained; exit 7"))
    (round3-output "HISTORY FAILED SHELL" (ogent-debug-last-tool)))
  (let* ((changed (list :tool "second-read" :args nil))
         (calls (list (list :tool "first-read" :args nil) changed))
         (write-runs 0)
         (ogent-tool-registry
          (list (list :name 'first-read :args nil
                      :effects '((:kind read :target file :scope workspace :risk low))
                      :function (lambda () (plist-put changed :tool "write-fixture") "first"))
                (list :name 'second-read :args nil
                      :effects '((:kind read :target file :scope workspace :risk low))
                      :function (lambda () "second"))
                (list :name 'write-fixture :args nil
                      :effects '((:kind write :target file :scope workspace :risk high))
                      :function (lambda () (cl-incf write-runs) "write fixture ran")))))
    (round3-output "BATCH CALL MUTATION" (ogent-agent-batch calls))
    (round3-output "BATCH WRITE RUNS" write-runs)))
