;;; independent.el --- Independent frozen-source contract probes -*- lexical-binding: t; -*-
(require 'ogent-agent)
(require 'ogent-tools)
(require 'ogent-tool-results)
(require 'ogent-tool-process)

(ert-deftest review12-real-gptel-unicode-request ()
  "Keep Unicode tool JSON intact through the actual FSM and wire serializer."
  (let* ((root (make-temp-file "review12-unicode-" t))
         (file (expand-file-name "é-λ-😀.txt" root))
         (text "β λ 😀 日本語")
         (ogent-tool-registry (copy-tree ogent-tools-default-registry))
         (ogent-tools-result-format 'json) (ogent-ledger-enabled nil)
         (ogent--tools-registered nil) (ogent--tool-specs-registered nil)
         (ogent--tool-formats-registered nil) (gptel--known-tools nil)
         (backend (gptel-make-openai "review12-local-serialization"
                                    :host "offline.invalid" :key "unused"
                                    :models '(local))))
    (unwind-protect
        (progn
          (with-temp-file file (insert text "\n"))
          (let* ((tool (ogent-tool-get "read-file"))
                 (value (funcall (gptel-tool-function tool) file 1 1))
                 (completed (list :id "local-first" :name "read-file" :args (list :file_path file)))
                 (pending (list :id "local-pending" :name "read-file"))
                 (fsm (gptel-make-fsm :info (list :backend backend :tool-use (list completed pending)))))
            (gptel--process-tool-call fsm tool completed value)
            (should-not (plist-get pending :result))
            (let* ((messages (gptel--parse-tool-results backend (list completed)))
                   (wire (gptel--json-encode (list :messages (vconcat messages))))
                   (parsed (json-parse-string wire :object-type 'plist))
                   (transport (plist-get (aref (plist-get parsed :messages) 0) :content))
                   (inner (json-parse-string transport :object-type 'plist)))
              (should (equal value transport))
              (should (equal (plist-get inner :status) "ok"))
              (should (equal (plist-get (plist-get inner :data) :path) file))
              (should (equal (plist-get (plist-get inner :data) :content) text)))))
      (delete-directory root t))))

(ert-deftest review12-serializer-shapes-nest ()
  "Direct, SDK, callback and doctor JSON remain valid nested Unicode text."
  (let* ((root (make-temp-file "review12-serializers-" t))
         (file (expand-file-name "λ.txt" root))
         (ogent-tool-registry (copy-tree ogent-tools-default-registry))
         (ogent-ledger-enabled nil) results (calls 0))
    (unwind-protect
        (progn
          (with-temp-file file (insert "λ 😀\n"))
          (push (ogent-tool--read-file file 1 1 'json) results)
          (push (ogent-agent-call "read" (list :file_path file) 'json) results)
          (push (ogent-doctor-format-json (list (list :id 'unicode :label "λ" :category 'environment
                                                     :status 'ok :detail "😀"))) results)
          (ogent-agent-call-async "read" (list :file_path file)
                                  (lambda (data) (cl-incf calls) (push data results)) 'json)
          (should (= calls 1))
          (dolist (value results)
            (should (multibyte-string-p value))
            (should (string-match-p "λ" value))
            (should (string-match-p "😀" value))
            (let ((outer (json-parse-string (json-serialize (list :content value)) :object-type 'plist)))
              (should (equal (plist-get outer :content) value))
              (should (json-parse-string (plist-get outer :content))))))
      (delete-directory root t))))

(ert-deftest review12-glob-raw-matched-excluded-and-legacy ()
  "Matched raw regular names error once; excluded names do not poison results."
  (let* ((root (make-temp-file "review12-raw-" t))
         (raw (concat root "/" (unibyte-string 255) ".txt"))
         (valid (expand-file-name "λ.el" root))
         (ogent-tool-registry (copy-tree ogent-tools-default-registry))
         (ogent-ledger-enabled nil))
    (unwind-protect
        (progn
          (with-temp-file raw (insert "raw"))
          (with-temp-file valid (insert "ok"))
          (should (file-regular-p raw))
          (dolist (pattern '("*.txt" "**/*.txt"))
            (dolist (format '(plist json))
              (let ((result (ogent-agent-call "files" (list :pattern pattern :path root) format)))
                (when (eq format 'json) (setq result (json-parse-string result :object-type 'plist)))
                (should (equal (plist-get (plist-get result :error) :code) "unsupported_output"))))
            (dolist (format '(plist json))
              (let ((calls 0) result)
                (ogent-agent-call-async "files" (list :pattern pattern :path root)
                                        (lambda (r) (cl-incf calls) (setq result r)) format)
                (should (= calls 1))
                (when (eq format 'json) (setq result (json-parse-string result :object-type 'plist)))
                (should (equal (plist-get (plist-get result :error) :code) "unsupported_output")))))
          (dolist (pattern '("*.el" "**/*.el"))
            (let ((result (ogent-agent-call "files" (list :pattern pattern :path root))))
              (should (equal (plist-get result :status) "ok"))
              (should (= (plist-get (plist-get result :data) :total_files) 1))
              (should (equal (plist-get (aref (plist-get (plist-get result :data) :files) 0) :path) valid))))
          (should (stringp (ogent-tool--glob "*.txt" root))))
      (delete-directory root t))))
